### ISSUE TITLE
Generated client code does not honor jackson mixins configuration

### ISSUE THREAD

**Issue by pacman1176** [stoicflame/enunciate#692] opened 2017-07-10 18:27 UTC
```xml
<modules>

  <java-json-client />

  <jackson>
    <mixin source="com.project.MyModelToStringSerializer" target="com.project.MyModel" />
  </jackson>

</modules>
```

The documentation and generated examples are correctly generated for instances of `MyModel` fields as specified in `MyModelToStringSerializer` to String as expected, but the generated clients (eg the java-json-client) do not. `MyModel` fields referenced in other models in the generated clients should be String as specified by the mixin, but they remain unchanged.

**Comment by stoicflame** [comment] 2017-09-27 21:42
Started looking at this.

Will you please show me what the `MyModelToStringSerializer` and `MyModel` classes look like?

**Comment by stoicflame** [comment] 2017-10-10 23:21
Moving to 2.11.

**Comment by stoicflame** [comment] 2018-04-13 16:30
Still haven't heard back, so I'm going to close this issue for now.

I'd be happy to re-open as needed if someone can provide details on how to reproduce the issue.

**Comment by matthew-pakulski** [comment] 2018-04-18 19:49
```java
public class MyModelToStringSerializer extends JsonSerializer<MyModel> {

  private MyModel value;

  @JsonCreator
  public MyModelToStringSerializer(MyModel value) {
    this.value = value;
  }

  @JsonValue
  public jsonValue() {
    // Special serialization handled here, in this case return a String of MyModel.getName() instead of a MyModel
    return value.getName();
  }
}

public class MyModel {
  private String name;
  public String getName() {
    return this.name;
  }
}
```

**Comment by stoicflame** [comment] 2018-05-03 17:55
So that's just not how Jackson mixins work. 

It looks like what you want is a `Converter` like what [this guy](http://blog.kavinarasu.com/programming/java/custom-deserialization-using-jackson-converter/) did.

Mixins are used to add annotations to classes, not convert them to a string. When I use the example code you provide above, Jackson does that same thing that Enunciate documents. So as far as I can tell, there's no bug here.

**Closed by stoicflame** 2018-05-03 17:55 UTC
Labels: bug
