### ISSUE TITLE
Data type with same names 

### ISSUE THREAD

**Issue by patvong** [stoicflame/enunciate#312] opened 2016-02-15 15:19 UTC
I have two data types with the same name in two different package e.g `com.my.package.A.UserInfo` and `com.my.package.B.UserInfo`.
Enunciate will only generated one single `json_userinfo.html` file. 
Also, in the swagger json output we will see both definition with the same name:
```
"json_userinfo" : {
  //...
},
"json_userinfo" : {
  //...
},
```
But the data type reference will always be the first one: `"$ref" : "#/definitions/json_userinfows"`
Is there a way to distinguish between the data types when they have the same name?

**Comment by stoicflame** [comment] 2016-02-16 05:31
Duplicate of #280 .

**Closed by stoicflame** 2016-02-16 05:31 UTC

**Comment by stoicflame** [comment] 2016-03-16 22:29
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
