### ISSUE TITLE
Generics are not taken into account to generate documentation?

### ISSUE THREAD

**Issue by victornoel** [stoicflame/enunciate#587] opened 2017-01-19 09:15 UTC
Hi,

I have the following type defined:
```
public static class JsonMap<K, V> {

        @Valid
        @JsonIgnore
        public final Map<K, V> map;

        public JsonMap(Map<K, V> map) {
            this.map = Collections.unmodifiableMap(map);
        }

        @JsonCreator
        private JsonMap(@Valid @JsonProperty("byId") Map<K, V> map, @JsonProperty("allIds") List<K> keys) {
            this(map);
            assert map.keySet().equals(new HashSet<>(keys));
        }

        @JsonProperty
        public Map<K, V> getById() {
            return map;
        }

        @JsonProperty
        public Set<K> getAllIds() {
            return map.keySet();
        }
    }
```

And I use it like this:
```
public class WorkspaceFullContent {

    @Valid
    @JsonProperty
    public final JsonMap<String, BusInProgress> busesInProgress;

    @Valid
    @JsonProperty
    public final JsonMap<String, BusFull> buses;

    ...
}
```

And the generated documentation is like this:
![image](https://cloud.githubusercontent.com/assets/160975/22100336/839b9dd4-de2f-11e6-83d4-61dcef7e4e69.png)
![image](https://cloud.githubusercontent.com/assets/160975/22100470/0eba0694-de30-11e6-9380-6c929ec1d0d0.png)

I think enunciate should be able to take the generics into account when possible during documentation generation.
In particular:
 - the example could take the generic into account, for example `BusInProgress` and `BusFull` are two different types and the example could contain their example (first screenshot)
 - the documentation of `WorkspaceFullContent` could at least details the generics in the `data type` column (second screeshot).

**Comment by stoicflame** [comment] 2017-01-19 15:01
Duplicate of #400 .

**Closed by stoicflame** 2017-01-19 15:01 UTC
Labels: enhancement
