### ISSUE TITLE
Issue with enunciate-jackson in 2.10.1: null:-1:-1 error: com.fasterxml.jackson.databind.module.SimpleModule

### ISSUE THREAD

**Issue by Barbatruuk** [stoicflame/enunciate#845] opened 2018-04-06 11:14 UTC
Also tried on 2.10.0, but same issue.

      <plugin>
        <groupId>com.webcohesion.enunciate</groupId>
        <artifactId>enunciate-maven-plugin</artifactId>
        <version>2.10.1</version>
        <executions>
          <execution>
            <goals>
              <goal>docs</goal>
            </goals>
            <configuration>
              <configFile>enunciate.xml</configFile>
              <docsDir>${project.build.directory}</docsDir>
            </configuration>
          </execution>
        </executions>
      </plugin>

I also added jackson-databind 2.9.5 dependency but I get the same error:

```
[INFO] Reflections took 1682 ms to scan 84 urls, producing 316 keys and 316 values
[WARNING] [ENUNCIATE] [javac] [ERROR] null:-1:-1 error: cannot access com.fasterxml.jackson.databind.module.SimpleModule
[WARNING] [ENUNCIATE] [javac] error: cannot access com.fasterxml.jackson.databind.module.SimpleModule
[WARNING] [ENUNCIATE] [javac]   class file for com.fasterxml.jackson.databind.module.SimpleModule not found
[WARNING] [ENUNCIATE] [javac]   Consult the following stack trace for details.
[WARNING] [ENUNCIATE] [javac]   com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.fasterxml.jackson.databind.module.SimpleModule not found
```

**Comment by stoicflame** [comment] 2018-04-09 14:52
That's one I haven't seen. Any way you can put together a sample project that reproduces the issue?

**Comment by stoicflame** [comment] 2018-04-16 16:45
It wouldn't hurt, but it appears to be some kind of class loading error, so I'm skeptical that a stack trace would give me much information. The problem seems to be in the environment and classpath setup, and I need some way to reproduce that.

**Comment by stoicflame** [comment] 2018-05-01 19:42
Bump.

Any word on this?

**Comment by stoicflame** [comment] 2018-05-07 22:35
No word yet. I'm going to close this until I hear back.

**Closed by stoicflame** 2018-05-07 22:35 UTC
Labels: support
