### ISSUE TITLE
No more than one JAX-RS entity parameter is allowed.. error with multiple @FormDataParam parameters

### ISSUE THREAD

**Issue by as6o** [stoicflame/enunciate#85] opened 2015-06-01 17:02 UTC
I have a resource defined like:

``` java
    @GET
    @Path("/test")
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    public String multipleFormParamTest(
            @FormDataParam("subject") FormDataBodyPart subjectPart,
            @FormDataParam("data") InputStream dataInputStream,
            @FormDataParam("data") FormDataBodyPart bodyPart
            ) {
        return "break";
    }
```

Jersey is perfectly happy with the above definition but enunciate is throwing the following error:
`error: [core] No more than one JAX-RS entity parameter is allowed (all other parameters must be annotated with one of the JAX-RS resource parameter annotations).`

Any reason why enunciate limits the number of @FormDataParam  parameters to only one?  Am I invoking enunciate incorrectly?

**Comment by stoicflame** [comment] 2015-06-01 20:35
Would there be some reason that the "jersey" module is disabled?

**Comment by as6o** [comment] 2015-06-01 21:15
Sorry - I was under the impression that the "jersey" module would produce jersey code/libraries to access the API.  I only need to produce documentation.

**Comment by stoicflame** [comment] 2015-06-01 22:06
Yes, so it also adds some of the jersey-specific implementation knowledge to the engine.

Does it adversely effect your build if you enable the Jersey module?

**Comment by as6o** [comment] 2015-06-02 14:03
Not at all.  I tried adding the Jersey module like so:

```xml
			<plugin>
				<groupId>org.codehaus.enunciate</groupId>
				<artifactId>maven-enunciate-slim-plugin</artifactId>
				<version>1.30</version>

				<configuration>
					<configFile>src/main/enunciate/enunciate.xml</configFile>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>assemble</goal>
						</goals>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>org.codehaus.enunciate</groupId>
						<artifactId>enunciate-docs</artifactId>
						<version>1.30</version>
					</dependency>
					<dependency>
						<groupId>org.codehaus.enunciate</groupId>
						<artifactId>enunciate-jersey</artifactId>
						<version>1.30</version>
					</dependency>
				</dependencies>
			</plugin>
```

And I still get the error.  My enunciate.xml is pretty simple:

```xml
<enunciate allowEmptyNamespace="true">
	<modules>
		<docs includeExampleJson="true" includeExampleXml="false" copyright=""></docs>
	</modules>
</enunciate>
```

I'm invoking via:
```mvn clean enunciate-slim:docs```

I've tried the non-slim version as well.  Same error.

**Comment by stoicflame** [comment] 2015-06-02 16:41
What version of Jersey are you using? What's the package of the `@FormDataParam` annotation?

**Comment by as6o** [comment] 2015-06-02 17:22
Package: org.glassfish.jersey.media.multipart.*
jersey-media-multipart (et al): 2.17
Java: JDK 1.7.0_45 (no 8 support yet :(

**Comment by stoicflame** [comment] 2015-06-02 18:11
Okay, so the annotation that Enunciate is looking for is `@com.sun.jersey.multipart.FormDataParam` (Jersey 1.0).

So for now, you'll need to provide the annotation as an explicit "custom resource parameter" in your config. I'll add the Jersey 2 annotation to the list of known annotations for the next Enunciate release.

```xml
<enunciate allowEmptyNamespace="true">
    <services>
        <rest>
            <custom-resource-parameter-annotation qualifiedName="org.glassfish.jersey.media.multipart.FormDataParam"/>
        </rest>
    </services>
    <modules>
        <docs includeExampleJson="true" includeExampleXml="false" copyright=""></docs>
    </modules>
</enunciate>
```

**Comment by stoicflame** [comment] 2015-09-23 22:39
Fixed in Enunciate 2.0.0.

**Comment by piyush-kunal** [comment] 2019-03-05 15:39
Getting the same error. 
" java.lang.IllegalStateException:  ......method has more than one entity parameter. You must use only one entity parameter"

	```
@POST
	@Path("/upload/{requestID}")	
	@Consumes(MediaType.MULTIPART_FORM_DATA)
        @Produces(MediaType.APPLICATION_JSON)
	public Response uploadFile(
			@PathParam("requestID") long projectId,
			@FormDataParam("file") InputStream inputStream,
			@FormDataParam("file") FormDataContentDisposition fileDetail
			) throws JSONException {
		
		EntityManager em = LeapUtils.getEm();	
		JSONObject obj = new JSONObject();
```
can you please tell me where i m doing wrong

**Comment by stoicflame** [comment] 2019-03-07 05:37
I'll reopen as a bug.

**Comment by stoicflame** [comment] 2019-08-10 21:49
I cannot reproduce the report that an error is given for this case. 
Here's a diff I applied to [enunciate-sample](https://github.com/stoicflame/enunciate-sample):

```diff
diff --git a/pom.xml b/pom.xml
index 08c659b..fe6043f 100644
--- a/pom.xml
+++ b/pom.xml
@@ -87,6 +87,12 @@
       <version>${jersey.version}</version>
     </dependency>
 
+    <dependency>
+      <groupId>org.glassfish.jersey.media</groupId>
+      <artifactId>jersey-media-multipart</artifactId>
+      <version>${jersey.version}</version>
+    </dependency>
+
     <dependency>
       <groupId>javax.servlet</groupId>
       <artifactId>javax.servlet-api</artifactId>
diff --git a/src/main/java/com/ifyouwannabecool/impl/FormService.java b/src/main/java/com/ifyouwannabecool/impl/FormService.java
new file mode 100644
index 0000000..aff23eb
--- /dev/null
+++ b/src/main/java/com/ifyouwannabecool/impl/FormService.java
@@ -0,0 +1,32 @@
+/*
+ * © 2019 by Intellectual Reserve, Inc. All rights reserved.
+ */
+package com.ifyouwannabecool.impl;
+
+import java.io.InputStream;
+import javax.ws.rs.Consumes;
+import javax.ws.rs.POST;
+import javax.ws.rs.Path;
+import javax.ws.rs.PathParam;
+import javax.ws.rs.Produces;
+import javax.ws.rs.core.MediaType;
+import javax.ws.rs.core.Response;
+
+import org.glassfish.jersey.media.multipart.FormDataContentDisposition;
+import org.glassfish.jersey.media.multipart.FormDataParam;
+
+@Path("/form")
+public class FormService {
+
+  @POST
+  @Path("/upload/{requestID}")
+  @Consumes(MediaType.MULTIPART_FORM_DATA)
+  @Produces(MediaType.APPLICATION_JSON)
+  public Response uploadFile(
+      @PathParam("requestID") long projectId,
+      @FormDataParam("file") InputStream inputStream,
+      @FormDataParam("file") FormDataContentDisposition fileDetail
+  ) {
+    return null;
+  }
+}
```

Please open a separate issue with a better description of what I need to do to see the problem.

**Closed by stoicflame** 2019-08-10 21:49 UTC
Labels: bug
