### ISSUE TITLE
Resource links in enunciate docs broken?

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#402] opened 2016-05-23 18:17 UTC
Hi.

I just encountered, that the link on the icon besides the resource endpoint in the enunciate documentation points to the wrong url. It e.g. points to:

`http://localhost:8080/pet-store/api/1categories`

So a slash is missing after the `1`.

But the service itself and the swagger ui works without a problem. It seems only the enunciate own docs to be affected. How is the link assembled?

I already tried to add a slash here:

```xml
		<jaxrs groupBy="path" datatype-detection="local">
			<application path="/pet-store/api/1" />
		</jaxrs>
```

but without any effect.

I'm missing something?

**Comment by stoicflame** [comment] 2016-05-23 21:18
Duplicate of #347.

**Closed by stoicflame** 2016-05-23 21:18 UTC
Labels: bug

**Comment by stoicflame** [comment] 2016-06-03 20:45
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).
