### ISSUE TITLE
Generic Types

### ISSUE THREAD

**Issue by DrawGrumpy** [stoicflame/enunciate#554] opened 2016-12-06 06:38 UTC
Hi,
in my Rest interface, I have a class with a generic type.
It will be great if the documentation generated show the class  and the attributes of generic type too.

Exemple : 
class Response<T> implements Serializable{
   private T data;
   private MetaData metaData;

   public T getData(){
      return data;
   }

   public MetaData getMetaData(){
      return metaData;
   }
}

public class Data implements Serializable {
    private String id;
    private String name;
    private int age;

    public String getId(){
        return id;
     }

    public String getName(){
        return name;
    }

    public int getAge(){
         return age;
    }

}

public interface TestRest {
   /**
     * returns a noval associated to an isin 
     * @param isin isin 
     * @returnWrapped java.lang.String
     */
    @GET
    @Path("/test/{id}")
    Response<Data> getTest(@PathParam("id") String id) throws AdvisoryFacadeException;
}

it will be great if in documentation the response like :  
{
   data : {
         id : "...",
         name : "...",
         age : 12345
    }
   metaData : {}
}

**Comment by stoicflame** [comment] 2016-12-06 17:12
Duplicate of #400.

**Closed by stoicflame** 2016-12-06 17:12 UTC
