### ISSUE TITLE
operationId length in swagger.json

### ISSUE THREAD

**Issue by vghero** [stoicflame/enunciate#718] opened 2017-09-04 07:33 UTC
Hi.

We're using 2.9.1 to generate SwaggerUI from our JAX-RS REST interfaces. Having the generated swagger.json, our clients use this to generate their typescript based clients via tooling. The problem that we encounter is, that the `operationId` in the swagger.json, that is used to generate the method names in the client code, gets _very_ long. It seems that enunciate uses the interface names separated by underscores to build this name. Since we use separate JAX-RS interfaces for collection and actual resource endpoints, this gets quite lengthy (e.g. `MenusResource_MenuResource_CategoriesResource_CategoryResource....`). Is there anyway this could be shortened? I assume this name must be unique? Maybe taking the path url without parameters could make it shorter. Or maybe provide an additional annotation/javadoc tag that could be set manually in the code to override the name could help?

**Comment by stoicflame** [comment] 2017-10-10 18:12
Duplicate of #652.

This seems to be a common issue, but I guess I'm not seeing where it becomes a problem. The `operationId` doesn't show up in the UI, does it?

**Comment by vghero** [comment] 2017-10-11 07:42
Well, the client guys complain, that the generated method names are too long (and they are right :)). They have to invoke the generated methods from the manually built code at some point and that looks really ugly :).

**Comment by stoicflame** [comment] 2017-10-11 13:45
What tool are you using to manually build code? What elements other than `operationId` get used? Does `operationId` get used directly or does it get "parsed" as described in #652 by assuming some kind of Noun_Verb convention?

**Comment by vghero** [comment] 2017-10-11 15:12
The frontend guys (angular) are using https://github.com/swagger-api/swagger-codegen for generation. The `operationId` is translated from 

`resource_Deliveries_DeliveriesResource_DeliveryResource_changeState_PUT`
to
`resourceDeliveriesDeliveriesResourceDeliveryResourceChangeStatePUT`
by the generator.

First I thought maybe using the URL could help here like translating

`GET /menus/{id}/categories/{id}/items/{id}`
to
`get_menus_byid_categories_byid_items_byid`
to
`getMenusByIdCategoriesByIdItemsById`
in the generator.

It would be most likely shorter and _maybe_ better readable and definitely unique.
But maybe hard to get "right" :(.

Left options would only be to use another template like you suggested in the other issue or provide some javadoc tag/annotation to set a unique "endpoint name" which would have to be checked for uniqueness in the end :(. I think the latter isn't worth it since it's more a technical problem. The first one seems flexible but I'm not sure what objects one can access in that template and if it's enough to build a unique name manually. E.g. is the URL accessible in the template :)?

**Closed** 2017-10-12 19:02 UTC
Labels: enhancement

**Comment by stoicflame** [comment] 2017-10-26 22:04
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
