### ISSUE TITLE
Slash removed in application path

### ISSUE THREAD

**Issue by murugaraja** [stoicflame/enunciate#359] opened 2016-04-04 06:15 UTC
Hello,

A follow-up question of  #356.
I used jaxrs to specify the Rest API path in enunciate docs. But it removed the last slash and merge with path.

Below is the enunciate.xml snippet i used.
<enunciate>
  <modules>
    <jaxrs>
      <application path="/v2/"/>

Expected  : http://site/project**/v2/**mypath
Displaying : http://site/project**/v2**mypath

Please suggest me the alternate way to achieve this, if it is a bug.

Thanks,
Raja.M

**Comment by stoicflame** [comment] 2016-04-04 14:02
Duplicate of #347 .

**Closed by stoicflame** 2016-04-04 14:02 UTC

**Comment by stoicflame** [comment] 2016-06-03 20:40
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).
