### ISSUE TITLE
Integers output with thousand-separators in swagger.json

### ISSUE THREAD

**Issue by jskovjyskebankdk** [stoicflame/enunciate#588] opened 2017-01-19 09:47 UTC
The validation for max value in this method:

````
	@GET  
	@Path("engagement/org/{orgUnitId}")
	@Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
	@TypeHint (value=EngagementHierarchy.class)
	public List<EngagementHierarchy> getEngagements(@PathParam("orgUnitId") @NotNull(message="orgUnitId mangler") 
										   @Min(value=0, message="hierarchyId canot be less than 0") 
										   @Max(value=Integer.MAX_VALUE, message="hierarchyId canot be above 2147483647") 
	                                       final int orgUnitId) {
		return service.getEngagements(orgUnitId);
	}
````

Results in swagger.json output like this:

````
    "\/engagement/org/{orgUnitId}" : {
      "get" : {
        "tags" : [ "Kunde" ],
        "operationId" : "resource_Kunde_getEngagements_GET",
        "produces" : [ "application/xml", "application/json" ],
        "parameters" : [
          {
            "name" : "orgUnitId",
            "in" : "path",
            "required" : true,
            "type" : "integer",
            "maximum" : 2,147,483,647,
            "minimum" : 0,
            "description" : ""
          }
        ],
        "responses" : {
...
````

The "pretty-printed" number 2,147,483,647 should have been output as 2147483647.

**Comment by stoicflame** [comment] 2017-01-19 15:02
Duplicate of #570 .

**Closed by stoicflame** 2017-01-19 15:02 UTC

**Comment by jskovjyskebankdk** [comment] 2017-01-19 15:27
Dang. Did check for existing bugs, but title did not reveal content.
Thanks!

**Comment by stoicflame** [comment] 2017-04-07 17:14
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
