### ISSUE TITLE
Default Pretty XML Issues

### ISSUE THREAD

**Issue by trevoreckersley** [stoicflame/enunciate#498] opened 2016-09-15 16:51 UTC
When configuring namespace mappings using the Enunciate XML file, I've experienced some unexpected issues which stem from the way the default namespace mapping is handled. Suppose we have the following partial XML config file:
```
<enunciate
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.6.0.xsd">
  <namespaces>
    <namespace id="atom" uri="http://www.w3.org/2005/Atom"/>
    <namespace id="gedcomx" uri="http://gedcomx.org/v1/"/>
    <namespace id="xml" uri="http://www.w3.org/XML/1998/namespace"/>
  </namespaces>
</enunciate>
```
No default namespace is specified; however, the `NamespacePropertiesArtifact` class will create a default namespace based on which schema has the most types (in this case, GedcomX). This behavior is unexpected, and causes problems when the `EnunciateJaxbNamespacePrefixMapper` is called. The result is the namespace is found in the collection of specified values, but because it is also the "default" namespace, the prefix to be returned is overridden and `""` is returned instead.

In addition, for some reason I have yet to determine, when `""` is returned as the namespace prefix, a `ns5:` prefix is attached in the output XML instead. This behavior also occurs when I specify a default attribute for the namespaces tag (e.g. `<namespaces default="http://gedcomx.org/v1/">...`) in addition to or in place of the namespace/id/uri tag.

Currently, I am able to work around the problem by specifying a blank ("") default namespace. While it works, it seems less than ideal. Example below:
```
<enunciate
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.6.0.xsd">
  <namespaces default="">
    <namespace id="atom" uri="http://www.w3.org/2005/Atom"/>
    <namespace id="gedcomx" uri="http://gedcomx.org/v1/"/>
    <namespace id="xml" uri="http://www.w3.org/XML/1998/namespace"/>
  </namespaces>
</enunciate>
```

**Comment by stoicflame** [comment] 2016-09-15 19:43
Yes, namespace handling is messy and quite counter-intuitive with JAXB. It should be much, much easier, but it's not.

FWIW, I've found that the reason JAXB makes up a namespace prefix (e.g. "ns5") for types that should be in the default namespace is that you've got _some_ element or class or type in your JAXB context that's defined in the empty namespace. If _anything_ is defined in the empty namespace, the empty namespace _must_ be the default namespace because XML apparently doesn't allow a namespace prefix to be assigned to the empty namespace (or at least JAXB doesn't allow it). So when the `EnunciateJaxbNamespacePrefixMapper` tells JAXB to make "http://gedcomx.org/v1/" the default namespace, JAXB silently ignores the suggestion and makes one up itself because there's some element in your context that's defined in the empty namespace.

I'm afraid the Enunciate classes are limited in what they can do. The only way to work around the issue is to configure Enunciate as you've described above, use your own NamespacePrefixMapper, or eliminate whatever type or element is defined in the empty namespace.

**Closed by stoicflame** 2016-09-15 19:43 UTC

**Comment by trevoreckersley** [comment] 2016-09-16 14:20
Thanks @stoicflame, that would explain the behavior. Are you open to the idea of changing to the `NamespacePropertiesArtifact` so that it does not assign an explicitly set namespace as a default? I believe that behavior would more sense than having the non-explicitly set default override an explicitly set value. I'd be willing to make the change and write up a pull request if you would be okay with it.

**Comment by stoicflame** [comment] 2016-09-16 14:27
What if somebody wanted to set a namespace as the default namespace? How would they do that?

**Comment by trevoreckersley** [comment] 2016-09-16 14:37
Currently, that works using `<namespaces default="http://example.com/chosen/namespace/">...`. The change I am proposing is that if there is no default set (just `<namespaces>`) then the auto-select default feature will not use an explicitly set entry as the default namespace. In other words, this:
```
<enunciate
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.6.0.xsd">
  <namespaces>
    <namespace id="atom" uri="http://www.w3.org/2005/Atom"/>
    <namespace id="gedcomx" uri="http://gedcomx.org/v1/"/>
    <namespace id="xml" uri="http://www.w3.org/XML/1998/namespace"/>
  </namespaces>
</enunciate>
```
Would *not* set `http://gedcomx.org/v1/` as the default namespace. If someone wanted to set it as the default, they could specify it like this:
```
<enunciate
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.6.0.xsd">
  <namespaces default="http://gedcomx.org/v1/">
    <namespace id="atom" uri="http://www.w3.org/2005/Atom"/>
    <namespace id="xml" uri="http://www.w3.org/XML/1998/namespace"/>
  </namespaces>
</enunciate>
```
Or if it was not specified explicitly as a default or mapped namespace, then it could be set as the default by the auto-default namespace mapper. In other words, this snippet would set `http://gedcomx.org/v1/` as the default namespace as well:
```
<enunciate
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.6.0.xsd">
  <namespaces>
    <namespace id="atom" uri="http://www.w3.org/2005/Atom"/>
    <namespace id="xml" uri="http://www.w3.org/XML/1998/namespace"/>
  </namespaces>
</enunciate>
```

**Comment by stoicflame** [comment] 2016-09-16 14:47
I see. Okay, I'm fine with that.

**Comment by trevoreckersley** [comment] 2016-09-16 14:48
Great! I'll get to work on writing up the modification.

**Comment by stoicflame** [comment] 2016-10-28 20:48
[Enunciate 2.7 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.7.0)
