### ISSUE TITLE
Wrong "array of array of type" documentation for List<type> definition in DTO

### ISSUE THREAD

**Issue by mscookies** [stoicflame/enunciate#491] opened 2016-08-29 16:21 UTC
Hello,
I'm using enunciate 2.6.0 to generate REST documentation from DTO and jax-rs interface definitions.
When I took a look at the generated docs, I realized that a
```java
public List<TypeDto> getMyTypes {
    return myTypes;
}
```
was documented as "array of array of type" and in the example it showed up like 
```json
"myTypes": [[{...}, {...}]]
```
Can you point out what I am doing wrong?

Regards
Michael

**Comment by stoicflame** [comment] 2016-08-29 16:30
Duplicate of #487.

**Closed by stoicflame** 2016-08-29 16:30 UTC
Labels: bug

**Comment by stoicflame** [comment] 2016-10-28 20:48
[Enunciate 2.7 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.7.0)
