### ISSUE TITLE
Support for @link and @see Javadoc tags

### ISSUE THREAD

**Issue by theCompanyDream** [stoicflame/enunciate#174] opened 2015-10-01 18:23 UTC
Is there a way to use the @see or @link for documentation that has already been generated below 
and I wanted to know if enunciate had a special way of connecting documents to each other

``` java
/**
 *
 * Service that uses rebuilds {@link ReportProblemSentence report} Report Problem Sentence Data Structure with suggested sentence
 *
 * @see ReportREST
 * @see ReportProblemSentenceREST
 *
 */
```

**Comment by stoicflame** [comment] 2015-10-01 18:39
Negative.

But we can keep this open as a feature request.

**Comment by anton-johansson** [comment] 2015-11-12 09:51
It would be very nice if this was implemented, atleast **@see**. Do you think this would ever be implemented?

We already have a few **@see** in our docs, which we will remove, but it seems pointless to do so if it would be implemented in a near future. :)

**Comment by stoicflame** [comment] 2015-11-12 15:03
I can take a closer look for 2.2, but I'm skeptical about the feasibility. These are the kinds of complexities that would need to be addressed:

* What happens if the `@see` or `@link` tags resolve to members or classes that aren't included in the API docs? (E.g. private interfaces, utility classes, packages, etc.)
* What happens if the tags resolve to a package?
* Since the members and classes are used in multiple places in the API, how do you know which ones the tags resolve to? Do they link to the XML or the JSON? Sometimes, this could be guessed by the context, but does that hold true all the time?

Anyway, why do you need to remove the `@see` tags? Enunciate should be just ignoring them. Are you seeing otherwise?

**Comment by anton-johansson** [comment] 2015-11-13 15:38
* I guess it would be up to the JavaDoc-writers to make sure that doesn't happen. But if it happens, I guess Enunciate could ignore them?
  * Not sure... Ignore it?
  * That's true... Not quite sure. We're planning on hiding the XML part all together, to make the documentation look as simple as possible and easy to navigate, and then I guess one alternative would be to configure which one of them the ```@link```'s lead to.

No, we don't have a problem with ```@see``` tags, only ```@link``` tags. They look rather bad in the documentation. So if this enhancement isn't developed, we'll remove all of them. :)

**Comment by stoicflame** [comment] 2015-11-13 16:23
Okay, so Enunciate should be stripping out those `@link` javadoc tags. That's definitely a bug, tracking at #213.

Enunciate should be replacing those tags with just the text, so this:

```java
/**
 * Each person has a {@link Name}
 */
```

Will be written to the docs as:

```html
<p>Each person has a Name</p>
```

That will definitely be fixed in Enunciate 2.2.

**Comment by theCompanyDream** [comment] 2015-11-15 20:52
> It would be very nice if this was implemented, atleast @link. Do you think this would ever be implemented? - anton-johansson 
I had envisioned enunciate linking to the html pages and if it wasn't available it would simply say page not found. After all should enunciate care if the page exists if it knows where it would be located? I think it should run a test checking to see all links worked. Any Thoughts?

**Comment by anton-johansson** [comment] 2015-11-16 07:32
@stoicflame Ahh, okay. I'll leave them then. :)

@theCompanyDream  Yeah, something like that. I guess we can at generation-time check if there are/will be generated documentation for the given ```@link```s and if so, simply wrap them in a ```<a ... />```-tag.

**Comment by pswvg** [comment] 2015-11-18 09:55
When {@link Name} is resolved to Name, will @Label taken into account :)? That would be great. So we have the correct javadoc linking within the source code (which allows refactoring etc.) and the automatic naming conversion for the documentation. That would save some time.

What about enums? {@link Status#ENABLED} could they also be resolved nicely?

**Comment by stoicflame** [comment] 2016-01-13 22:33
Update: this issue isn't going to make it into 2.2.

**Comment by vgcookies** [comment] 2016-05-12 14:37
Is this a possible candidate for 2.4.0 :)?

**Comment by stoicflame** [comment] 2016-05-12 15:57
I don't think so. :frowning: 

It's a lot of work because there's a lot of complexity, and I'm having a hard time seeing myself mustering the time and resources to get it done.

**Comment by stoicflame** [comment] 2016-12-16 21:31
This enhancement is currently seeking a sponsor. If anybody is willing to sponsor the work, [reach out to me](http://webcohesion.com/#contact) and I'd be happy to pick it up.

**Comment by stoicflame** [comment] 2017-03-30 18:59
Thanks to the support of a generous sponsor, this issue has been implemented and will be included in 2.9.

**Closed by stoicflame** 2017-03-30 18:59 UTC
Labels: enhancement, seeking sponsor

**Comment by stoicflame** [comment] 2017-04-07 17:16
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)

**Comment by vghero** [comment] 2017-08-26 09:28
Hi.

I just tried 1.31 with this on a sub resource interface and `@link` on parameter description was just rendered as text but not as a link. Is this expected behavior :)?

```
    /**
     * Returns the platform resource.
     *
     * @param platformIdOrType id or type of the platform. See {@link PlatformType}.
     * @return the platform resource.
     */
    @Path(PlatformResource.PLATFORM_ID_OR_TYPE_PATH)
    PlatformResource getPlatformResource(
            @PathParam(PlatformResource.PLATFORM_ID_OR_TYPE_PATH_PARAM) String platformIdOrType);
```

**Comment by stoicflame** [comment] 2017-08-28 15:13
See #703.

**Comment by vghero** [comment] 2017-08-28 15:15
Thanks!
