### ISSUE TITLE
Execution default of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.2.0:assemble failed: Enunciate compile failed.

### ISSUE THREAD

**Issue by yeahbutwalter** [stoicflame/enunciate#260] opened 2016-01-20 08:34 UTC
We used v1.31 with jdk7 previously for quite some time, no problems whatsoever. After upgrading to java8 and latest&greatest Enunciate we encounter the following:

Maven 3.3
Javac 1.8.0_60

Maven snippet is default example for docs, no custom modules.

Maven output:

```
[WARNING] [ENUNCIATE] [javac] [WARNING] null:-1:-1 warning: [options] bootstrap class path not set in conjunction with -source 1.7
[WARNING] [ENUNCIATE] [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
[WARNING] [ENUNCIATE] [javac] [ERROR] null:-1:-1 error: cannot access org.joda.convert.ToString
[WARNING] [ENUNCIATE] [javac] error: cannot access org.joda.convert.ToString
[WARNING] [ENUNCIATE] [javac]   class file for org.joda.convert.ToString not found
[WARNING] [ENUNCIATE] [javac]   Consult the following stack trace for details.
[WARNING] [ENUNCIATE] [javac]   com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.joda.convert.ToString not found
[WARNING] [ENUNCIATE] [javac]   Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
[WARNING] [ENUNCIATE] [javac]           at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:101)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:81)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
[WARNING] [ENUNCIATE] [javac]           at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
[WARNING] [ENUNCIATE] [javac]           at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
[WARNING] [ENUNCIATE] [javac]           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[WARNING] [ENUNCIATE] [javac]           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[WARNING] [ENUNCIATE] [javac]           at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] foo ............................... FAILURE [ 32.161 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.224 s
[INFO] Finished at: 2016-01-20T00:26:12-08:00
[INFO] Final Memory: 27M/336M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.2.0:assemble (default) on project foo: Execution default of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.2.0:assemble failed: Enunciate compile failed. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.2.0:assemble (default) on project foo: Execution default of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.2.0:assemble failed: Enunciate compile failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.2.0:assemble failed: Enunciate compile failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: com.webcohesion.enunciate.EnunciateException: Enunciate compile failed.
        at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:708)
        at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:368)
        at com.webcohesion.enunciate.mojo.AssembleBaseMojo.execute(AssembleBaseMojo.java:86)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :foo
```

Any ideas?

Much obliged.

**Comment by stoicflame** [comment] 2016-01-20 20:41
Seems like the problem is that the class `org.joda.convert.ToString` isn't on the Enunciate classpath. Can you confirm?

If you run "mvn -X", you'll get a bunch of extra output that shows the compiler classpath. You'll probably want to take a look at that to see if the right jar is there.

**Comment by mahileeb** [comment] 2016-01-21 21:47
We hit the same issue and it was due to joda-time 2.9 not properly declaring it's dependency on joda-convert (it's marked as optional)

**Comment by stoicflame** [comment] 2016-01-21 22:05
Thanks, @mahileeb.

So the solution is to add joda-convert to the classpath.

**Closed by stoicflame** 2016-01-21 22:05 UTC
Labels: support

**Comment by mahileeb** [comment] 2016-01-21 22:08
Correct, looks like they will fix it in version 2.9.2

**Comment by stoicflame** [comment] 2016-03-16 22:34
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).

**Comment by ronnyfm** [comment] 2019-01-22 18:00
> Thanks, @mahileeb.
> 
> So the solution is to add joda-convert to the classpath.

Sorry, can you provide an example on how to do it on Maven? I am getting the same error message, I am using Enunciate 2.11.1

**Comment by mahileeb** [comment] 2019-01-22 21:32
@ronnyfm just add joda-convert to your module dependencies
```
 <dependencies>
     <dependency>
                <groupId>org.joda</groupId>
                <artifactId>joda-convert</artifactId>
                <version>2.1.2</version>
     </dependency>
 </dependencies>
```

**Comment by mahileeb** [comment] 2019-01-23 04:12
@ronnyfm I'm not sure what else to suggest sorry!
