### ISSUE TITLE
WrapRootValue only works for XmlRootElement and not for XmlType

### ISSUE THREAD

**Issue by KishoreGGK** [stoicflame/enunciate#776] opened 2017-11-23 10:20 UTC
I have a file 

```java
@XmlType (name = "test")
public class Test {
private String testattr
.
.
.
}
```

When I use wrapRootValue= true, Enunciate generate the following,

```java
{
Test: {
testattr:""
}
}
```

When I use wrapRootValue= true, Enunciate generate the,

However, if 

```java
@XmlRootElement (name = "test")
public class Test{
private String testattr;
.
.
.
} 
```

In this case, when I use wrapRootValue= true, the generated document is,

```java
{
test: {
testattr:""
}
}
```

See "Test" instead of "test" whereas in xmlrootement its correct "test"

**Comment by stoicflame** [comment] 2017-11-27 18:08
Please confirm that you've configured the jackson module to honor jaxb annotations:

```xml
<enunciate>
  <modules>
    <jackson honorJaxb="true"/>
```

**Comment by KishoreGGK** [comment] 2017-11-28 03:25
Confirming that I have set honorJaxb = true setting.

Sorry, my post may be misleading. When I annotate with @XmlRootElement i get correct behavior i.e "test" which is matching with the "name" attribute of annotation, and when i annotate with @XmlType i get "Test" instead of "test" (test is the value of the name attribute in @XmlType).

I have update my previous comment correctly.

**Comment by stoicflame** [comment] 2017-11-28 18:41
Duplicate of #772

**Closed by stoicflame** 2017-11-28 18:41 UTC
Labels: bug

**Comment by stoicflame** [comment] 2018-05-08 16:15
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
