### ISSUE TITLE
collapse-type-hierarchy non-functional?

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#432] opened 2016-06-16 16:55 UTC
Hi.

I re-tested this bug: https://github.com/stoicflame/enunciate/issues/408 with `2.5.0`.

activating `collapse-type-hierarchy` like so in enunciate.xml:

```xml
...
	<modules>
 		<jackson dateFormat="string" collapse-type-hierarchy="true" />
...
```

doesn't seem to do the trick to hide abstract superclasses e.g. on DTOs. They are still shown in the "overview" page. I thought this is fixed but I encountered that I used `@Ignore` on them. So removing the annotation also shows the abstract superclasses on the JSON page.

Can someone confirm this? What effect has the collapse option in detail? Or should have :)?

**Comment by stoicflame** [comment] 2016-08-10 22:47
I'm afraid I'm going to need more details, because superclasses aren't added to the docs for me when `collapse-type-hierarchy` is `true`.

I _did_ happen to notice that if any of my accessors or collections or maps referenced the abstract superclass, then it is added to the model. But I think this is working as designed because there's no way for Enunciate to tell what instance is actually going to be used.

So, for example if `collapse-type-hierarchy` is `true` and I have an object model that has class `Dog` inherit from `Animal`, then the `Animal` type is correctly hidden in the docs. However, if I have another class, `Zoo` that has a property e.g. `List<Animal> getAnimals()`, then class `Animal` is going to get added to the generated documentation.

For now I'm going to close this. I'd be happy to re-open if needed.

**Closed by stoicflame** 2016-08-10 22:47 UTC
Labels: support
