### ISSUE TITLE
Text formatting in Javadoc preformatted text blocks

### ISSUE THREAD

**Issue by gmtwc** [stoicflame/enunciate#203] opened 2015-11-03 20:02 UTC
It appears that Enunciate strips the space / tabs in Javadoc preformatted text blocks:

```java
/**
* ...
*<pre>
Test line1
    - Text line 2
    - Text line 3
*</pre>
*/
```

procuces comment:

Text line 1
- Text line 2
- Text line 3

**Comment by stoicflame** [comment] 2015-11-03 20:03
Duplicate of #77.

**Closed by stoicflame** 2015-11-03 20:03 UTC

**Comment by gmtwc** [comment] 2015-11-03 20:37
Thanks for the reference.

As a workaround I did include the line containing "&nbsp;" annotation after \<pre> and the whole block text formatting is preserved now.
