### ISSUE TITLE
TypeHint (NO_CONTENT) showing in object list

### ISSUE THREAD

**Issue by droche-cafex** [stoicflame/enunciate#301] opened 2016-02-05 13:37 UTC
NO_CONTENT listed as an Object - This is due to the TypeHint annotation. Without it the docs will show "Object (JSON)" as a datatype.

When NO_CONTENT TypeHint is used perhaps there shold be no hyperlink and not be included in the list of objects in the generated API doc?

**Comment by stoicflame** [comment] 2016-02-08 17:57
Thanks for the report.

**Comment by stoicflame** [comment] 2016-03-11 18:54
Duplicate of #261; fixed at 4494880.

**Closed by stoicflame** 2016-03-11 18:54 UTC
Labels: bug

**Comment by stoicflame** [comment] 2016-03-16 22:33
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
