### ISSUE TITLE
Description part of @RequestHeader is not properly inserted to html file

### ISSUE THREAD

**Issue by MyeongJaeKim** [stoicflame/enunciate#439] opened 2016-06-21 08:10 UTC
Hi,

Let us assume that we have this method,

```java
/**
 Explains about this method.... blahblah...

@RequestHeader Accept application/xml
*/
public ResponseBody someRestfulApi(....)
{
}
```

The **application/xml** is description part of **@RequestHeader** tag.
When build was over, instead of **application/xml**, the "Explains.." is inserted to Request Parameters description area.

This area is located at after **<caption>Request Parameters</caption>**.

I believe this is parser bug.

**Comment by vguna** [comment] 2016-06-30 11:06
I have a similar (?) problem. For me, when only using `@RequestHeader` (no `@param`) and using `@HeaderParam` in the method signature, the header appears in the documentation, but the description of it is empty. If I add `@param` refering to the `@HeaderParam` name, it takes the `@param` for documentation.

Example with empty description:

```java
	/**
	 * Header param test.
	 *
	 * @RequestHeader Authorization the key of the header.
	 */
	@GET
	@Consumes(MediaType.APPLICATION_XML)
	void testHeader(@HeaderParam("Authorization") String key);
```

**Comment by MyeongJaeKim** [comment] 2016-07-04 03:26
I've made pull request fixing this issue.

**Comment by stoicflame** [comment] 2016-08-17 22:15
I've been looking at this issue, but I can't reproduce the problem. If I copy the JavaDoc as you have it above, it works fine for me and I don't see what you're describing. Also, the pull request doesn't make any effective change since `getJavaDoc().toString()` will return the same thing as `getDocValue()`.

@vguna, the issue you report is working as designed. The way to document parameters is using the `@param` JavaDoc tag, not the `@RequestHeader` tag.

Closing this issue for now. I'd be happy to re-open if you can show me how to reproduce the problem.

**Closed by stoicflame** 2016-08-17 22:15 UTC
Labels: bug

**Comment by vgcookies** [comment] 2016-08-18 06:55
Mkay. So `@RequestHeader` is only for values that aren't part of the method signature?

**Comment by vguna** [comment] 2016-08-18 06:56
Mkay. So `@RequestHeader` is only for values that aren't part of the method signature?

**Comment by stoicflame** [comment] 2016-08-18 14:48
That's the idea, yes.
