### ISSUE TITLE
Support for disabling DataTypes overview

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#963] opened 2019-05-28 13:35 UTC
Currently I have an API that has some duplicate models in terms of naming. So e.g. two `Address` objects (on purpose). Those of course show up twice in the JSON Datatypes overview. Sometimes there are even 3-4 e.g. on "generic" enum namings like `Type`. Seeing them all listed on the overview is quite confusing. One could start prefixing them with the parent object name, making them somehow unique like `ModificationType`, `ItemType` etc. But that's cumbersome to do. An easy option would be, to just disable the JSON Datatypes completely from the overview and just keeping the actual resources as an entry point to the documentation. This also feels more natural and models are still linked and reachable from the resource documentation.

So it would be nice, if there would be something like `<docs disableDataTypesOverview="true>` to remove the type listing (but keep the models and examples on the resources documentation).

**Comment by stoicflame** [comment] 2019-08-08 19:42
Duplicate of #916 .

**Closed by stoicflame** 2019-08-08 19:42 UTC
Labels: enhancement

**Comment by stoicflame** [comment] 2019-08-12 15:25
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
