### ISSUE TITLE
Support for enums as method parameters?

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#485] opened 2016-08-24 12:21 UTC
Hi.

I'm using 2.6.0 to generate the documentation for my JAX-RS server interfaces.
I've got one endpoint where an enum is used in the method signature like this:

``` java
    /**
     * Updates the order status for the specified order identifier.
     *
     * @param status
     *            the order status to set.
     * @return the updated order.
     */
    @PUT
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @Path(ORDER_STATUS_PATH)
    OrderDto setStatus(OrderDto.Status status);
```

This works so far, but the request documentation for it looks like this:

```
PUT /orders/{orderId}/status
Content-Type: application/json
Accept: application/json


...


```

I know, this is probably an edge-case - using enums in the method like this. Is it worth to add support for it :)?

**Comment by stoicflame** [comment] 2016-08-24 18:06
Is the issue that you don't like seeing the template parameters (e.g. `{orderId}`) in the path? You'd like them replaced with one of the possible values?

Maybe.

What if the type were a string or integer? What value do I put in there?

I'm also not totally convinced that it's the right thing to do because it "hides" the path parameter. If I'm reading these as documentation, I kind of _like_ seeing the path parameter in there, no?

**Comment by vguna** [comment] 2016-08-24 18:58
Ah, no :). I meant the example with the three dots. I would expect that there should be something displayed like:

```json
{
   "status" : "NEW"
}
```` 

Instead of the three dots. At least that's what jackson creates.

**Comment by stoicflame** [comment] 2016-08-24 21:37
I see. Well, I can take a closer look for 2.7.

**Comment by stoicflame** [comment] 2016-10-26 16:03
I spent some time looking into this. The problem is that I can't figure out what it interpreting that JSON object as an instance of `OrderDto.Status`. When I try to duplicate the same method signature and send the same JSON, I get an error from the JSON processor saying it has no way of translating `"{ "status" : "NEW" }"` into an instance of `OrderDto.Status`. But sending just `"NEW"` works.

I'm thinking you must have some kind of special-case JSON configuration on your side that allows you to do the custom JSON processing.

With that assumption, I'm going to close this as "will not fix" because there's no way for Enunciate to know how that enum is going to be processed.

**Comment by vguna** [comment] 2017-03-25 12:17
I again stumbled across this in another project. My earlier assumption regarding that the json should look like this:

```json
{
    "status": "NEW"
}
```

was incorrect. Actually jackson expects something like this:

`"NEW"`

instead, as you correctly pointed out already.

So would it be possible to show `"<enumvalue>"` instead of the `...` in the example?

Thanks.

**Closed** 2017-03-30 23:05 UTC
Labels: bug

**Comment by stoicflame** [comment] 2017-04-07 17:20
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
