### ISSUE TITLE
Enunciate 2: Maven Eclipse fails with NoClassDefFoundError

### ISSUE THREAD

**Issue by pohndorff** [stoicflame/enunciate#138] opened 2015-09-11 12:06 UTC
Hello,

I saw that you updated to M4 but I can't build any version newer than M2 with Maven using Eclipse for Java. I'm receiving the following error message:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building <project_name> 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ <project_name> ---
[INFO] Deleting /Users/<user_name>/Desktop/java/<project_name>/target
[INFO] 
[INFO] --- enunciate-maven-plugin:2.0.0-M.4:assemble (assemble) @ <project_name> ---
[INFO] Reflections took 797 ms to scan 35 urls, producing 54 keys and 54 values 
warning: [options] bootstrap class path not set in conjunction with -source 1.5
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
/Users/<user_name>/Desktop/java/<project_name>/target/enunciate/java-json-client/src/javax/ws/rs/core/Response.java:26: error: cannot find symbol
  private javax.ws.rs.core.StatusType _statusInfo;
                          ^
  symbol:   class StatusType
  location: package javax.ws.rs.core
/Users/<user_name>/Desktop/java/<project_name>/target/enunciate/java-json-client/src/javax/ws/rs/core/Response.java:118: error: cannot find symbol
  public javax.ws.rs.core.StatusType getStatusInfo() {
                         ^
  symbol:   class StatusType
  location: package javax.ws.rs.core
/Users/<user_name>/Desktop/java/<project_name>/target/enunciate/java-json-client/src/javax/ws/rs/core/Response.java:126: error: cannot find symbol
  public void setStatusInfo(javax.ws.rs.core.StatusType _statusInfo) {
                                            ^
  symbol:   class StatusType
  location: package javax.ws.rs.core
3 errors
4 warnings
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.527 s
[INFO] Finished at: 2015-09-11T13:49:39+01:00
[INFO] Final Memory: 31M/163M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.4:assemble (assemble) on project <project_name>: Execution assemble of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.4:assemble failed: com.webcohesion.enunciate.EnunciateException: Compile failed of Java client-side classes. OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: com/webcohesion/enunciate/modules/java_xml_client/SimpleNameForMethod
    at com.webcohesion.enunciate.modules.java_xml_client.JavaXMLClientModule.generateClientSources(JavaXMLClientModule.java:136)
    at com.webcohesion.enunciate.modules.java_xml_client.JavaXMLClientModule.call(JavaXMLClientModule.java:118)
    at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
    at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
    at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
    at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
    at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
    at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
    at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
    at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
    at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
    at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
    at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

I'm not sure if this is caused by a problem on my side or not. Maybe you can help. Building the project with M2 works fine but I need the Response bodies for my docs.

**Comment by stoicflame** [comment] 2015-09-11 17:17
I'm afraid I can't seem to reproduce the problem. I'm not an Eclipse user, but I downloaded it, installed m2eclipse, opened a sample project, ran it, and it worked fine for me. I'm attaching a screenshot.

However, at #137 there's another report of `NoClassDefFoundError`s. I'm going to assume this is the same thing, close it out, and track the `NoClassDefFoundError`s over there.

But I'm kind of blocked on that issue until someone can come up with a way for me to reproduce the problem...


![eclipse-screenshot-successful-build](https://cloud.githubusercontent.com/assets/145838/9821299/ae5bef82-5876-11e5-96d1-82c6301a460d.png)

**Comment by stoicflame** [comment] 2015-09-16 20:05
Okay, the client-side compile failures about `StatusType` were fixed (see #137). However, I still can't explain, nor can I reproduce the `NoClassDefFoundError`s that surface when building with Eclipse. So I'm going to re-open this issue to track the work.

However, I'm not going to hold up the release for this issue because (1) it appears to be environment-specific (Eclipse) and (2) I haven't been able to reproduce the issue.

**Comment by ke5stl** [comment] 2016-01-15 18:33
hey there.  I am trying to use enunciate 2.2.0 with a maven project, and I'm getting the following:

Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.2.0:assemble (assemble) on project bcpbx-rest-war: Execution assemble of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.2.0:assemble failed: com.webcohesion.enunciate.EnunciateException: Compile failed of Java JSON client-side classes. OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.2.0:assemble (assemble) on project bcpbx-rest-war: Execution assemble of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.2.0:assemble failed: com.webcohesion.enunciate.EnunciateException: Compile failed of Java JSON client-side classes.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution assemble of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.2.0:assemble failed: com.webcohesion.enunciate.EnunciateException: Compile failed of Java JSON client-side classes.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:144)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.RuntimeException: com.webcohesion.enunciate.EnunciateException: Compile failed of Java JSON client-side classes.
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:656)
	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:368)
	at com.webcohesion.enunciate.mojo.AssembleBaseMojo.execute(AssembleBaseMojo.java:86)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	... 20 more
Caused by: com.webcohesion.enunciate.EnunciateException: Compile failed of Java JSON client-side classes.
	at com.webcohesion.enunciate.modules.java_json_client.JavaJSONClientModule.compileClientSources(JavaJSONClientModule.java:317)
	at com.webcohesion.enunciate.modules.java_json_client.JavaJSONClientModule.call(JavaJSONClientModule.java:121)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
	at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
	at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
	at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
	at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:101)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:81)
	... 31 more


For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ENUNCIATE] /Users/darkos/yyy-api/yyy-api-project/trunk/modules/yyy-rest-common/war/target/enunciate/java-xml-client/src is NOT up-to-date because it's an empty directory.
[ENUNCIATE] Generating the Java client classes...
[ENUNCIATE] Processing template null.
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: com/webcohesion/enunciate/modules/java_xml_client/JavaXMLClientModule$2
	at com.webcohesion.enunciate.modules.java_xml_client.JavaXMLClientModule.processTemplate(JavaXMLClientModule.java:305)
	at com.webcohesion.enunciate.modules.java_xml_client.JavaXMLClientModule.generateClientSources(JavaXMLClientModule.java:253)
	at com.webcohesion.enunciate.modules.java_xml_client.JavaXMLClientModule.call(JavaXMLClientModule.java:123)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
	at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
	at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
	at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
	at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


here is what I have in my pom, for the plugin: enunciate.version is 2.2.0 by the way....

            <plugin>
                <groupId>com.webcohesion.enunciate</groupId>
                <artifactId>enunciate-maven-plugin</artifactId>
                <version>${enunciate.version}</version>
                <executions>
                    <execution>
                        <id>assemble</id>
                        <goals>
                            <goal>assemble</goal>
                        </goals>
                        <configuration>
                            <project-extensions>
                                <extension>java-json-client</extension>
                                <extension>java-xml-client</extension>
                            </project-extensions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

I am using jdk 8 u 66.

**Comment by stoicflame** [comment] 2016-12-16 21:29
This issue has been stale for a year an a half. I'm going to close it until someone can provide more information about how to reproduce it.

**Closed by stoicflame** 2016-12-16 21:29 UTC
Labels: bug
