### ISSUE TITLE
JavaDoc description blocks @documentationExample

### ISSUE THREAD

**Issue by volongithub** [stoicflame/enunciate#663] opened 2017-05-29 11:33 UTC
Hi,

first of all, thank you for the work you put into enunciate providing a great tool.

We switched from 2.8.0 to 2.9.1 and I recognized, that the `@documentationExample` java doc "enhancement" does no longer work, if there is some java doc description. 
Heres an example of a Domain Object with Java Doc and the `@documentationExample`

```
/**
 * The filename of the corresponding file. It must match the FilePattern
 *
 * @documentationExample 899899899899_20170309_ident
 */
@XmlElement
private String fileName;
```
In the generated Documentation the example is missing:

```
_someother_
"fileName" : "...",
_someother_
```
If I delete the Java Doc description, the example is generated correctly:
```
/**
  * @documentationExample 899899899899_20170309_ident
  */
@XmlElement
private String fileName;
```
```
 "fileName" : "899899899899_20170309_ident",
```
It also seems, that there must not be any empty line before `@documentationExample`. Otherwise the example won't get generated either.

We are also using Lombok and the following Annotations on the Class:
```
@XmlRootElement
@XmlAccessorType(XmlAccessType.NONE)
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
```

It is reproducable, that the same code with documentation and maven and enunciate settings does generate correctly with 2.8.1 but not with 2.9.1.
I need 2.9.1 (or 0) because of the _`@link`_ feature.

This problems occurs also on any Code which is not in my project, but referenced via the maven.xml and ununciate.xml

I can't find any hints in the WIKI or the closed issues, so could you please help? Maybe I am missing some new settings or dependencies?
Thank you in advance, vol.

**Comment by stoicflame** [comment] 2017-06-19 20:45
Sounds like a bug; I'll take a look for 2.10.0

**Comment by stoicflame** [comment] 2017-09-06 19:42
I'm afraid I can't reproduce this. I tried to do so my applying this diff to the [enunciate-sample](https://github.com/stoicflame/enunciate-sample) app:

```diff
diff --git a/src/main/java/com/ifyouwannabecool/domain/persona/Name.java b/src/main/java/com/ifyouwannabecool/domain/persona/Name.java
index ac37d26..21cec67 100644
--- a/src/main/java/com/ifyouwannabecool/domain/persona/Name.java
+++ b/src/main/java/com/ifyouwannabecool/domain/persona/Name.java
@@ -16,13 +16,21 @@
 
 package com.ifyouwannabecool.domain.persona;
 
+import com.fasterxml.jackson.annotation.JsonAutoDetect;
+
 /**
  * A name of a persona.
  *
  * @author Ryan Heaton
  */
+@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY, getterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE)
 public class Name {
 
+  /**
+   * The given name.
+   *
+   * @documentationExample mygiven
+   */
   private String givenName;
   private String surname;
 ```

And I get the example correctly showing up, with the JavaDoc:

![image](https://user-images.githubusercontent.com/145838/30131178-0bfadc4c-9309-11e7-89c3-c66f00cae545.png)

Can you provide more details about how to reproduce this issue?

**Comment by volongithub** [comment] 2017-09-11 08:06
I have a maven project structure with 3 layers.

1.  Application Parent
      1. Business Service Parent
            1. Domain Classes
            1. api-docs
            1. REST Service

For a Basic example I left off the REST Service and just created an example Project with a Domain Class.

Here's the Domain class:
```java
@XmlRootElement
@XmlAccessorType(XmlAccessType.NONE)
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class File {
   /**
    * @documentationExample 899899899899_20170309_ident
    */
   @XmlElement
   private String filename;

   /**
    * The filesuffix indicates the file type
    *
    * @documentationExample csv
    * @documentationExample txt
    */
   @XmlElement
   private String fileSuffix;
}
```
The Domain project has some company internal dependencies and beanutils:
```xml
[...]
<dependency>
    <groupId>commons-beanutils</groupId>
    <artifactId>commons-beanutils</artifactId>
    <version>1.9.3</version>
</dependency>
[...]
```
The api-docs projects has the following dependencies:
```xml
<dependencies>
   <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>${fasterxml.version}</version>
      <scope>provided</scope>
   </dependency>
   <dependency>
      <groupId>org.jboss.weld.servlet</groupId>
      <artifactId>weld-servlet</artifactId>
      <version>${weld.version}</version>
      <scope>provided</scope>
   </dependency>
   <dependency>
      <groupId>de.example.business</groupId>
      <artifactId>business-service-domain</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
   </dependency>
</dependencies>
```
This is the enunciate plugin config:
```xml
<plugin>
   <groupId>com.webcohesion.enunciate</groupId>
   <artifactId>enunciate-maven-plugin</artifactId>
   <executions>
      <execution>
         <goals>
            <goal>assemble</goal>
         </goals>
         <configuration>
            <configFile>src/enunciate.xml</configFile>
            <skipEnunciate>${enunciate.skip}</skipEnunciate>
         </configuration>
      </execution>
   </executions>
</plugin>
```
And this is the enunciate.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.8.0.xsd">
    <title>Example Business Module</title>
    <api-license>Example Corp.</api-license>
    <copyright>Example Corp.</copyright>

    <application root="/api" />

    <modules>
        <csharp-xml-client disabled="true" />
        <c-xml-client disabled="true" />
        <gwt-json-overlay disabled="true" />
        <spring-web disabled="true" />
        <obj-c-xml-client disabled="true" />
        <ruby-json-client disabled="true" />
        <php-xml-client disabled="true" />
        <php-json-client disabled="true" />
        <javascript-client disabled="true" />
        <java-xml-client disabled="true" />
        <jackson1 disabled="true"/>
        <docs faviconUri="favicon.ico"/>
        <docs forceExampleJson="true"/>
    </modules>

    <api-classes>
        <include pattern="de.example.business.**" />
    </api-classes>
</enunciate>
```
The maven output does not have any errors:
```
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ business-service-api-docs ---
[INFO] Deleting C:\git\api-doc-example\business-service\api-docs\target
[INFO] 
[INFO] --- enunciate-maven-plugin:2.9.1:assemble (default) @ business-service-api-docs ---
[INFO] [ENUNCIATE] Using enunciate configuration at C:\git\api-doc-example\business-service\api-docs\src\enunciate.xml
[INFO] Reflections took 514 ms to scan 44 urls, producing 13 keys and 13 values 
[INFO] [ENUNCIATE] No resource APIs registered: Swagger UI will not be generated.
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ business-service-api-docs ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
```
With that setup I get this result:
![enunciate_file_missing_example](https://user-images.githubusercontent.com/29040077/30263934-2addfe06-96d7-11e7-8b1a-4bae7d24385a.png)
**If I remove the javadoc and the blank line**
```
/**
    * @documentationExample csv
    * @documentationExample txt
*/
@XmlElement
private String fileSuffix;
```
The example is generated correctly:
![enunciate_file_examples_ok](https://user-images.githubusercontent.com/29040077/30264015-6d084a20-96d7-11e7-820c-8e6f24d8889a.png)

**Comment by stoicflame** [comment] 2017-09-25 20:53
Thanks for your patience. I've tried to follow your instructions, but I'm still not seeing it.

Will you checkout [branch "enunciate-663" from the enunciate-sample](https://github.com/stoicflame/enunciate-sample/tree/enunciate-663) and modify it so I can see the problem?

**Comment by volongithub** [comment] 2017-09-28 09:29
Hi, sorry for the late response. Thank you for taking time in that issue.
There is lot of work I have to take care of, but I will try to check out the example and reproduce my problem as soon as I can.

**Comment by stoicflame** [comment] 2017-10-10 23:18
Moving to 2.11...

**Comment by stoicflame** [comment] 2018-04-13 16:29
Since I haven't heard back, I'm going to close this issue for now.

If someone can provide a way to reproduce the problem, I'd be happy to reopen.

**Closed by stoicflame** 2018-04-13 16:29 UTC
Labels: bug
