### ISSUE TITLE
@requestExample is not generating properly in swagger.json output

### ISSUE THREAD

**Issue by pippy44** [stoicflame/enunciate#1071] opened 2021-02-02 15:10 UTC
I am using enunciate 2.13.2 for a spring mvc based project and I am trying to add the @requestExample and @responseExample annotations to some of my endpoints. The swagger file is generated and the endpoints are created, but I am only ever seeing correct output from the @responseExample annotation. I've tried supplying json to the request and response examples in the file format and creating it in the documentation itself like so:
` * @requestExample application/json { "name" : "Harry Truman", "birth" : "1884-05-08" }`

Again it only works for the @responseExample annotation. The things I have noticed with the @requestExample is that when I use it on an endpoint that has a parameter annotated with @RequestBody, the example specified in @requestExample is not generated in the swagger.json at all. If I remove the @RequestBody annotation, then I do receive output. It creates a new parameter for the endpoint like so:
``` 
{
  "name" : "body",
  "required" : false,
  "in" : "body",
  "schema" : {
    "description" : "",
    "type" : "file"
  },
  "description" : ""
}
```

I've tried copying the example from here https://github.com/stoicflame/enunciate/blob/master/examples/spring-petclinic/src/main/java/org/springframework/samples/petclinic/web/TestRestController.java and still no luck. Further, I even checked out the enunciate project, and it doesn't look like this example is working in that project either.

**Comment by stoicflame** [comment] 2021-02-02 17:55
Thanks for the report. I'll take a look.

**Comment by pippy44** [comment] 2021-02-03 16:54
On another note, it looks like the name for a body parameter that is generated is always set to body. In this example, https://github.com/stoicflame/enunciate/blob/master/examples/spring-petclinic/src/main/java/org/springframework/samples/petclinic/web/TestRestController.java, the swagger output names the body parameter body instead of testBody. Is there a reason for this/a way to change the name?

**Comment by stoicflame** [comment] 2021-02-03 17:22
There's no way to change the name in the swagger output, no. It's never been requested. If you'd like to requests an enhancement, go ahead and open up a new issue with what mechanisms you'd like to have available for changing or configuring that.

**Comment by imindloop** [comment] 2021-02-23 23:13
Hello all, looking for a friend on this:

I'm using enunciate 2.12.1 to generate a swagger specification, and then use swagger-codegen-cli-3.0.12, to then create an html report:

I'm using the @responseExample annotation in this manner:
`
/**
* @responseExample application/json file:[full-path-to-file-in-filesystem]/item-example.json
* @throws Exception if something went wrong
@GET
`

And the content of the item-example.json file is:
`{
    "type": "object",
    "properties": {
        "refreshDate": {
            "type": "string",
            "format": "date-time",
            "example": "2021-02-19"
        },
        "displayName": {
            "type": "string",
            "example": "Joan.Sebastian"
        },
        "active": {
            "type": "boolean",
            "example": true
        }
    }
}`

And instead of getting this json in the root element "Definitions", so it can be rendered in the gray box for examples in the html, I get it in the "responses -> schema -> examples" for the "path" element corresponding to the endpoint where the annotation was used, what is the right way to use annotation? or what is the right format for the json file? or what am I doing wrong?

Thanks beforehand for your help.

**Comment by stoicflame** [comment] 2021-02-24 16:53
@imindloop it seems like you're misunderstanding the use of the `@responseExample` annotation. That annotation is used to provide an example of the JSON that the endpoint produces, but you seem to think that it can be used to provide the _schema_ for the JSON that the endpoint produces.

Is that an accurate/helpful observation?

**Comment by imindloop** [comment] 2021-02-24 17:04
Hello Ryan, first of all, thanks for taking the time to reply to my question.

Yes, I understood that it was meant to automatically populate the schema from the rest endpoint. 

What I understand from what you're saying is that @responseExample will not output the json, or xml, or the content of the file in the path to the specification, it would be an in-place documentation, so it would be accessible only by going to the actual REST endpoint code, or by opening the file in the path, am I right?

Could you please point me to a way to populate the schema in the specification from enunciate? 

Thanks again Ryan.

**Comment by stoicflame** [comment] 2021-02-24 17:39
There are no hooks to directly edit the swagger schema. Enunciate is a tool to _generate_ that schema from Java code. The way to adjust the schema is to provide Java code that defines the correct schema.

**Comment by imindloop** [comment] 2021-02-25 20:37
Thanks again Ryan!

I upgraded Swagger-Codegen from 3.0.12 to 3.0.24 and now I get the response example in the html file produced by Codegen.

**Comment by pippy44** [comment] 2021-03-23 17:44
@stoicflame Why has this issue been marked as closed? Is there a fix out for it?

**Comment by stoicflame** [comment] 2021-03-23 17:55
My impression what that the issue was resolved with [this comment](https://github.com/stoicflame/enunciate/issues/1071#issuecomment-786187388).

**Comment by pippy44** [comment] 2021-03-23 17:56
@stoicflame I believe he is referring to responseExample which indeed does work just fine. The original issue though is that requestExample does not work correctly.

**Comment by stoicflame** [comment] 2021-03-23 17:58
Okay, I'll reopen and take a look.

**Comment by pippy44** [comment] 2021-03-23 18:03
Alright, thanks.

**Comment by imindloop** [comment] 2021-05-05 21:07
So is @requestExample supported or is only documented but not supported?

I'm using examples from the documentation itself without any luck, for example:

/**
 * @requestExample application/json { "name" : "Harry Truman", "birth" : "1884-05-08" }
 * @requestExample application/xml
 *   <person>
 *     <name>Harry Truman</name>
 *     <birth>1884-05-08</birth>
 *   </person>
 */
 
 And anyways that's not getting into the json specification.

**Comment by stoicflame** [comment] 2021-05-05 21:42
There is support for it, but I still need to investigate reports that it's not working.

**Comment by stoicflame** [comment] 2022-03-15 21:09
I've finally gotten around to looking at this issue.

So:

`@responseExample` annotation seems to be working as designed, correct?

`@requestExample` annotation is not used in the generated Swagger UI.

`@requestExample` _is_ working as designed in the generated Enunciate documentation.

Is that correct?

If so, then I think this issue means we need to get `@requestExample` working in the Swagger UI. Can someone show me an example `swagger.json` file that contains a correct request example? Enunciate currently uses OpenAPI 2.0 for its schema, and I can't find anywhere in [the documentation](https://swagger.io/specification/v2/) that describes how OpenAPI 2.0 supports request examples.

**Comment by stoicflame** [comment] 2023-03-14 21:14
Support added for OpenAPI 3.0, including request examples.

**Closed by stoicflame** 2023-03-14 21:14 UTC
Labels: bug

**Comment by imindloop** [comment] 2023-03-16 13:17
Thank you!

I was laid off from that job, I may not need that feature myself, but it's
great other users can benefit.
