### ISSUE TITLE
Error while generating docs

### ISSUE THREAD

**Issue by kingferiol** [stoicflame/enunciate#521] opened 2016-10-13 16:39 UTC
Hi all

Using this wonderful toll i'm facing this errors an i can't understand how to proceed

			<plugin>
				<groupId>com.webcohesion.enunciate</groupId>
				<artifactId>enunciate-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>docs</goal>
						</goals>
						<configuration>
							<sourcepath-includes>
								<include>
									<groupId>com.mycompany.rest.api</groupId>
								</include>
							</sourcepath-includes>
							<docsDir>${project.build.directory}/apidoc</docsDir>
						</configuration>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>com.mycompany.rest.api</groupId>
						<artifactId>rest-api</artifactId>
						<version>10.7.3-SNAPSHOT</version>
					</dependency>
				</dependencies>
			</plugin>

<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.0.0-M.3.xsd">

	<api-classes>
		<include pattern="com.mycompany.*"/>
	</api-classes>

	
	<jaxb datatype-detection="aggressive"/>
	
</enunciate>

[DEBUG] [ENUNCIATE] Freemarker processing output:

[WARNING] [ENUNCIATE] [javac] [ERROR] com.webcohesion.enunciate.Enunciate$URLFileObject[file:/C:/devtool/repository/com/webcohesion/enunciate/enunciate-core/2.6.0/enunciate-core-2.6.0.jar!/com/webcohesion/enunciate/Nothing.java]:18:36 /C:/devtool/repository/com/webcohesion/enunciate/enunciate-core/2.6.0/enunciate-core-2.6.0.jar!/com/webcohesion/enunciate/Nothing.java:18: error: package com.webcohesion.enunciate.metadata does not exist
[WARNING] [ENUNCIATE] [javac] /C:/devtool/repository/com/webcohesion/enunciate/enunciate-core/2.6.0/enunciate-core-2.6.0.jar!/com/webcohesion/enunciate/Nothing.java:18: error: package com.webcohesion.enunciate.metadata does not exist
[WARNING] [ENUNCIATE] [javac] @com.webcohesion.enunciate.metadata.Ignore
[WARNING] [ENUNCIATE] [javac]

**Comment by stoicflame** [comment] 2016-10-13 16:45
Yes, this is a duplicate of #520. See the suggested workaround in the comments.

**Closed by stoicflame** 2016-10-13 16:45 UTC

**Comment by kingferiol** [comment] 2016-10-14 15:52
Thanks to the quick answer and of course solution. 

Can I have another question (probably it is not the right place but let me try).

I'm interested in create a .war with enunciate + swagger-ui only and i'm failing at the moment.

I have already read to this https://github.com/stoicflame/enunciate-sample. Do you have additional suggestion.

**Comment by stoicflame** [comment] 2016-10-14 17:07
What does "failing" mean? Is there some kind of error?

**Comment by kingferiol** [comment] 2016-10-17 13:39
I had an empty WAR but I did a mistake.

To make a test I have changed the folder for result and this lead to have an empty WAR. 

Now I have to solve the last 2 issue and i have done. I'm stacked with basic authentication and examples

**Comment by stoicflame** [comment] 2016-10-28 20:49
[Enunciate 2.7 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.7.0)
