### ISSUE TITLE
List size constraint lets task fail

### ISSUE THREAD

**Issue by Crashkurs** [stoicflame/enunciate#590] opened 2017-01-20 15:23 UTC
When annotating a List with @Size, make it required and set its min or max value above 1 000 000, the jackson parser generates a "." after every 3 digits, which lets enunciate fail with 
```java
com.webcohesion.enunciate.EnunciateException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('.' (code 46)): was expecting comma to separate OBJECT entries
 at [Source: java.io.FileReader@74c9a4cc; line: 21, column: 34]
```

Setup:

1. build.gradle

```gradle
plugins {
  id "java"
  id "com.webcohesion.enunciate" version "2.8.0"
}

dependencies {
  compile group: 'org.glassfish.jersey.media', name: 'jersey-media-json-jackson', version: '2.25'
  compile group: 'org.glassfish.jersey.ext', name: 'jersey-bean-validation', version: '2.25'
}
```
2. enunciate.xml
```xml
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.0.0.xsd">

  <api-classes>
    <include pattern="org.example.com.resources.**"/>
  </api-classes>
  <modules>
    <ruby-json-client disabled="true"/>
    <java-json-client disabled="true"/>
    <php-json-client disabled="true"/>
    <gwt-json-overlay disabled="true"/>
    <javascript-client disabled="true"/>
    <c-xml-client disabled="true"/>
    <csharp-xml-client disabled="true"/>
    <java-xml-client disabled="true"/>
    <obj-c-xml-client disabled="true"/> 
    <php-xml-client disabled="true"/>
  </modules>
</enunciate>
```

3. ExampleResource

```java
package org.example.com.resources;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.core.Response;
import org.example.com.resources.model.Container;

@Path("/")
public class ExampleResource {

    @Path("example")
    @GET
    public Response getExample(Container container) {
        return Response.ok().build();
    }
}
```

4. Container

```java
package org.example.com.resources.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.LinkedList;
import java.util.List;
import javax.validation.constraints.Size;

public class Container {

    @JsonProperty(required = true)
    @Size(min = 1, max = 1000000)
    private final List<SingleItem> items = new LinkedList<>();

    public List<SingleItem> getItems() {
        return items;
    }
}
```

5. SingleItem

```java
package org.example.com.resources.model;

public class SingleItem {

    private String property;

    public String getProperty() {
        return property;
    }

    public void setProperty(String property) {
        this.property = property;
    }
}
```

6. Result
```json
"json_Container" : {
      "type" : "object",
      "title" : "Container",
      "required" : ["items"],
          "properties" : {
            "items" : {
            "minItems" : 1,
            "maxItems" : 1.000.000,
"description" : "",
"type" : "array",
"items" : {
  "$ref" : "#/definitions/json_SingleItem"
}
            }
          },
      "example" : {
  "items" : [ {
    "property" : "..."
  }, {
    "property" : "..."
  } ]
},
      "description" : ""
    }
```

7. Expected
```json 
"maxItems" : 1000000,
```

**Comment by stoicflame** [comment] 2017-01-20 16:27
Duplicate of #588 and #570

**Closed by stoicflame** 2017-01-20 16:27 UTC
Labels: bug

**Comment by stoicflame** [comment] 2017-04-07 17:15
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
