### ISSUE TITLE
Jaxb generated source classes lead to compile errors in java-xml-client

### ISSUE THREAD

**Issue by Thorndike** [stoicflame/enunciate#843] opened 2018-03-23 09:21 UTC
I am using enunciate 2.10.1. I already created an issue about being not able to exclude these  generated classes from the build ( #842 ). The problem that occurs with those generated classis is that the contain named inner classes which are not correctly handled when generation the xml client. For example a return of an inner class results in a generated reference that is missing the outer class.

```
public XmlProductAuskunftData.Onlineauskunftkapitels getOnlineauskunftkapitels()
leads to
public de.creditreform.crefoteam.ctocrefoportal.ctoproductfactory.domain.v1.Onlineauskunftkapitels getOnlineauskunftkapitels() {
                                                                             ^
  symbol:   class Onlineauskunftkapitels
  location: package de.creditreform.crefoteam.ctocrefoportal.ctoproductfactory.domain.v1
/home/raucha/entwicklung/ask/ask-auskunft/head/ask-auskunft/api/target/enunciate/java-xml-client/src/de/creditreform/crefoteam/ctocrefoportal/ctoproductfactory/domain/v1/XmlProductAuskunftData.java:59: error: cannot find symbol
```

In the resulting code the outer class XmlProductAuskunftData is missing from the generated code which leads to the compile error.

**Comment by stoicflame** [comment] 2018-05-02 22:25
I'm sure there's a bug in Enunciate, but I can't see it yet. I've been trying to reproduce the problem, but there must be something I'm doing differently.

Here's a diff I applied to [enunciate-sample](https://github.com/stoicflame/enunciate-sample):

```diff
diff --git a/src/main/java/com/ifyouwannabecool/api/PersonaService.java b/src/main/java/com/ifyouwannabecool/api/PersonaService.java
index a1b238d..0494733 100644
--- a/src/main/java/com/ifyouwannabecool/api/PersonaService.java
+++ b/src/main/java/com/ifyouwannabecool/api/PersonaService.java
@@ -14,6 +14,7 @@ import javax.ws.rs.Path;
 import javax.ws.rs.PathParam;
 import javax.ws.rs.Produces;
 
+import com.ifyouwannabecool.domain.persona.OuterThing;
 import com.ifyouwannabecool.domain.persona.Persona;
 
 /**
@@ -33,6 +34,10 @@ public interface PersonaService
     @GET
     Persona readPersona(@PathParam("id") String personaId);
 
+    @Path("/thing")
+    @GET
+    OuterThing.InnerThing readInnerThing();
+
     @Path("/{id}.json")
     @GET
     @Produces("application/json")
diff --git a/src/main/java/com/ifyouwannabecool/domain/persona/OuterThing.java b/src/main/java/com/ifyouwannabecool/domain/persona/OuterThing.java
index 25acbe2..8d31c8f 100644
--- a/src/main/java/com/ifyouwannabecool/domain/persona/OuterThing.java
+++ b/src/main/java/com/ifyouwannabecool/domain/persona/OuterThing.java
@@ -1,7 +1,15 @@
 package com.ifyouwannabecool.domain.persona;
 
+import javax.xml.bind.annotation.XmlRootElement;
+
 /**
  *
  */
 public class OuterThing {
+
+  @XmlRootElement
+  public static class InnerThing{
+
+    public String name;
+  }
 }
diff --git a/src/main/java/com/ifyouwannabecool/impl/PersonaServiceImpl.java b/src/main/java/com/ifyouwannabecool/impl/PersonaServiceImpl.java
index 72b8b7a..48cbf15 100644
--- a/src/main/java/com/ifyouwannabecool/impl/PersonaServiceImpl.java
+++ b/src/main/java/com/ifyouwannabecool/impl/PersonaServiceImpl.java
@@ -11,6 +11,7 @@ import javax.ws.rs.Path;
 
 import com.ifyouwannabecool.api.PermissionDeniedException;
 import com.ifyouwannabecool.api.PersonaService;
+import com.ifyouwannabecool.domain.persona.OuterThing;
 import com.ifyouwannabecool.domain.persona.Persona;
 
 /**
@@ -28,6 +29,11 @@ public class PersonaServiceImpl implements PersonaService
         return persona;
     }
 
+    @Override
+    public OuterThing.InnerThing readInnerThing() {
+        return null;
+    }
+
     public Persona readPersonaJson()
     {
         final Persona persona = new Persona();
```

I added a method that returns an inner class, but everything seems to work fine.

Can you modify the diff in a way that exposes the problem for me?

**Comment by Thorndike** [comment] 2018-05-03 05:25
Send you a mail with the offending file to check.

**Comment by stoicflame** [comment] 2018-05-03 16:49
The source code classes aren't quite enough for me to debug the issue because there are a bunch of other classes that they reference; I can't compile it.

What if you sent me the original schema file from which the classes were generated?

**Comment by Thorndike** [comment] 2018-05-04 05:19
That is a problem, it's a very large xsd which contains quite some proprietary infos that I am not allowed to share in other Types.

**Comment by stoicflame** [comment] 2019-08-10 21:57
This issue appears stalled. I'm closing it as "will not fix" for now. I'll re-open if we can figure out a way for me to reproduce the error.

**Closed by stoicflame** 2019-08-10 21:57 UTC
Labels: support
