### ISSUE TITLE
Unable to add Description for Resources

### ISSUE THREAD

**Issue by NoelToy** [stoicflame/enunciate#1203] opened 2024-03-27 05:07 UTC
am using Enunciate 2.14.0 on SpringBoot Rest API project. The issue is that I am not able to add description to any of the resources. I am using Enunciate Docs module to generate the API document. @stoicflame  can you please help me out with this? Is the feature of providing description for resources is available in Enunciate? If yes can I know how? Because I wasn't able to find any documentation on it.

NB: Am attaching some images for reference.![IMG_20240327_103519.jpg](https://github.com/stoicflame/enunciate/assets/39144336/c12c8ea6-24a5-48ff-8cf2-9f41fe51b73d)

![IMG_20240327_103543~2.jpg](https://github.com/stoicflame/enunciate/assets/39144336/cb0ca118-33a6-4004-a2f3-6dde54850657)

![IMG_20240327_103446.jpg](https://github.com/stoicflame/enunciate/assets/39144336/459b1eb1-700a-459d-b1be-67a4ef4ebe1f)

**Comment by stoicflame** [comment] 2024-03-27 17:34
Can you please try "grouping" the resources by "class" and see if that gives you what you need?

```xml
<enunciate>
  <modules>
    <spring-web groupBy="class"/>
```

**Comment by NoelToy** [comment] 2024-03-29 01:26
Hi @stoicflame thanks for the reply, but I have added <spring-web groupBy="class"/> yet in the documentation it's not reflecting. It would be so helpful is you could help me figure out this.

NB: For reference I am attaching the image of properties.![IMG_20240329_065357~2.jpg](https://github.com/stoicflame/enunciate/assets/39144336/ade759b7-cc08-47ba-b606-2e2e826ff6da)

**Comment by stoicflame** [comment] 2024-03-29 06:13
I'm afraid I can't reproduce your problem. Documentation at the resource level is captured fine in all my testing environments and applications.

The only way I can see forward to help you is if you can provide an example project that manifests the problem.

**Comment by NoelToy** [comment] 2024-03-30 18:26
Sure I can give you a base implementation for the project. But even before that could you please share an example of how the description is give for each api in Enunciate? If you can share an example it would be grateful as I can find out where am going wrong.

**Comment by stoicflame** [comment] 2024-03-30 21:54
You can always check out the [enunciate-sample](https://github.com/stoicflame/enunciate-sample) app.

**Comment by stoicflame** [comment] 2024-06-18 19:34
Closing for now; happy to reopen as needed.

**Closed by stoicflame** 2024-06-18 19:34 UTC
Labels: support
