### ISSUE TITLE
Build fails using Maven 3.5.2

### ISSUE THREAD

**Issue by ronnyfm** [stoicflame/enunciate#763] opened 2017-11-01 20:28 UTC
Hello,

I am getting the following message, after I updated to Maven 3.5.2 (it worked with 3.3.9 and 3.5.0).

Logs mention a **RolesAllowed** annotation (not being used in my code).

```
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.10.1:docs (docs) on project my-project.services: freemarker.core._TemplateModelException: An error has occurred when reading existing sub-variable "securityRoles"; see cause exception! The type of the containing value was: extended_hash+string (com.webcohesion.enunciate.modules.jaxrs.api.impl.MethodImpl wrapped into f.e.b.StringModel)
[ERROR]
[ERROR] ----
[ERROR] FTL stack trace ("~" means nesting-related):
[ERROR] 	- Failed at: #assign securityRoles = method.securi...  [in template "jar:file:/Users/ronny.fallas/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.10.1/enunciate-docs-2.10.1.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "processResourceGroup" at line 562, column 11]
[ERROR] 	~ Reached through: #nested  [in template "jar:file:/Users/ronny.fallas/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.10.1/enunciate-docs-2.10.1.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "boilerplate" at line 141, column 9]
[ERROR] 	~ Reached through: @boilerplate title=(title + ": " + re...  [in template "jar:file:/Users/ronny.fallas/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.10.1/enunciate-docs-2.10.1.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "processResourceGroup" at line 518, column 5]
[ERROR] 	- Reached through: @file name=(resourceGroup.slug + ".ht...  [in template "jar:file:/Users/ronny.fallas/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.10.1/enunciate-docs-2.10.1.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "processResourceGroup" at line 517, column 3]
[ERROR] 	- Reached through: @processResourceGroup resourceGroup=r...  [in template "jar:file:/Users/ronny.fallas/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.10.1/enunciate-docs-2.10.1.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" at line 238, column 11]
[ERROR] 	~ Reached through: #nested  [in template "jar:file:/Users/ronny.fallas/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.10.1/enunciate-docs-2.10.1.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "boilerplate" at line 141, column 9]
[ERROR] 	~ Reached through: @boilerplate pagenav=pagenav  [in template "jar:file:/Users/ronny.fallas/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.10.1/enunciate-docs-2.10.1.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" at line 192, column 3]
[ERROR] 	- Reached through: @file name=indexPageName  [in template "jar:file:/Users/ronny.fallas/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.10.1/enunciate-docs-2.10.1.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" at line 181, column 1]
[ERROR] ----: InvocationTargetException: javax/annotation/security/RolesAllowed: javax.annotation.security.RolesAllowed
```

Using 2.5.0 but updating to the latest version (2.10.1) doesn't work either, same error.

**Comment by stoicflame** [comment] 2017-11-01 20:50
Confirmed.

**Comment by stoicflame** [comment] 2017-11-01 21:00
I haven't been able to figure out any workaround yet. I've opened [MNG-6298](https://issues.apache.org/jira/browse/MNG-6298) for the Maven developers to triage.

In the meantime, if anybody can find a workaround I'd be happy to hear it.

**Comment by raner** [comment] 2017-11-03 17:10
In terms of a work-around, I was able to get rid of the problem by simply adding the missing dependency to enunciate's <plugin> configuration:

```
        <dependencies>
          <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.3</version>
          </dependency>
        </dependencies>
```

**Comment by ronnyfm** [comment] 2017-11-03 22:16
Workaround confirmed. Thank you!

**Comment by stoicflame** [comment] 2017-11-06 18:09
Thanks for the workaround. I had earlier attempted adding `jsr250-api` to the plugin classpath, but that didn't fix the issue. I wonder what it is about `javax.annotation-api` that does the trick. Ideas?

```xml
<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>jsr250-api</artifactId>
    <version>1.0</version>
</dependency>
```

**Comment by jgcollings** [comment] 2017-12-21 22:10
I ran into this as well using the maven:3-jdk-8 docker container since they updated maven to 3.5.2. I fixed it by running the build within the maven:3.3-jdk-8 docker container. This is another work-around until a permanent solution is found.

**Comment by ronanbrennan** [comment] 2018-01-03 20:17
Confirmed I also had the issue on Maven 3.5.2. 

I attempted combinations of the workarounds from both @raner and @stoicflame, and I still kept getting the same error. Issue was present with Enunciate versions 2.8.0, 2.8.1 and 2.10.1. Switched to maven 3.3.9 and everything worked fine.

**Comment by sbrattla** [comment] 2018-01-12 10:34
Had this issue using Maven 3.5.2 as well. Switched to 3.3.9, and it works.

**Comment by stoicflame** [comment] 2018-01-19 22:29
https://issues.apache.org/jira/browse/MNG-6298 has been resolved as fixed in 3.5.3. I don't see any downloads of that version available yet, though.

**Comment by derekm** [comment] 2018-01-26 03:41
I'm also seeing this! I will have to wait for Maven 3.5.3 to be released before I can merge Enunciate into my Jenkins builds. Thanks for your work, btw!

**Comment by raviharshil27** [comment] 2018-03-10 02:02
Just update- i had the same issue with maven 3.5.2, but it works with Maven 3.5.3

**Comment by ronnyfm** [comment] 2018-03-12 16:08
And Maven 3.5.3 is available now. Thanks for your support.

**Closed** 2018-03-12 16:08 UTC
Labels: bug
