### ISSUE TITLE
Exclude generated class JAXB 

### ISSUE THREAD

**Issue by AlexGuion** [stoicflame/enunciate#372] opened 2016-04-19 12:56 UTC
Hi,

I have a soap webservice which uses a class generated by JAXB. This class is generated only one time an put in my project, Then i try to generate Enunciate documentation, it fails to create it with this error :

 ```
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.3.0:docs (docs) on project ContractLib: freemarker.core._TemplateModelException: An error has occurred when reading existing sub-variable "dataType"; see cause exception! The type of the containing value was: extended_hash+string (com.webcohesion.enunciate.modules.jaxb.api.impl.PropertyImpl wrapped into f.e.b.StringModel)
[ERROR] 
[ERROR] ----
[ERROR] FTL stack trace ("~" means nesting-related):
[ERROR] - Failed at: @referenceDataType referenceType=prop...  [in template "jar:file:/D:/m2repo-3.1.1/com/webcohesion/enunciate/enunciate-docs/2.3.0/enunciate-docs-2.3.0.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "processDataType" at line 974, column 46]
[ERROR] - Reached through: @file name=(type.slug + ".html")  [in template "jar:file:/D:/m2repo-3.1.1/com/webcohesion/enunciate/enunciate-docs/2.3.0/enunciate-docs-2.3.0.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "processDataType" at line 902, column 3]
[ERROR] - Reached through: @processDataType type=type  [in template "jar:file:/D:/m2repo-3.1.1/com/webcohesion/enunciate/enunciate-docs/2.3.0/enunciate-docs-2.3.0.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "processDataSyntax" at line 887, column 13]
[ERROR] - Reached through: @file name=(syntax.slug + ".html")  [in template "jar:file:/D:/m2repo-3.1.1/com/webcohesion/enunciate/enunciate-docs/2.3.0/enunciate-docs-2.3.0.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "processDataSyntax" at line 865, column 3]
[ERROR] - Reached through: @processDataSyntax syntax=syntax  [in template "jar:file:/D:/m2repo-3.1.1/com/webcohesion/enunciate/enunciate-docs/2.3.0/enunciate-docs-2.3.0.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" at line 270, column 9]
[ERROR] - Reached through: @file name=indexPageName  [in template "jar:file:/D:/m2repo-3.1.1/com/webcohesion/enunciate/enunciate-docs/2.3.0/enunciate-docs-2.3.0.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" at line 165, column 1]
[ERROR] (Hidden 8 "~" lines for terseness)
[ERROR] 
[ERROR] ----: InvocationTargetException: A type definition must be supplied. OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
```

So i tried to exclude the generated class by exclude it on the enunciate.xml but at the compile enunciate say : 
```
[WARNING] [ENUNCIATE] Added outils.onixack.ONIXMessageAcknowledgement as a JAXB type definition even though is was supposed to be excluded according to configuration. It was referenced from produitCompteRendu(service.bean.ack.OnixAckWSBean) of service.bean, so it had to be included to prevent broken references.
```

So my only option, is to exclude the all service, which contains this class, at the moment.

I work  with : 
Enunciate plugin 2.3.0
java 7
generete my class with  : xjc -d aDirectory  ONIX_BookProduc_3.0_reference_nons.xsd
We can find the xsd on : http://www.editeur.org/93/Release-3.0-Downloads/
the file : ONIX for Books 3.0.2 XSD Schema + Codelists Issue 32.zip

**Comment by stoicflame** [comment] 2016-04-19 13:37
Sounds like a bug. Thanks for the report.

**Comment by stoicflame** [comment] 2016-05-23 20:55
Put some effort into fixing this today, but I'm having a hard time setting up the environment.

Are you using Ant or Maven?

It would be nice if you included the full stack trace, not just the freemarker error.

I tried to download the XSD that you referenced, but I could only find "ONIX for Books 3.0.3 XSD Schema + Codelists Issue 33.zip" not "ONIX for Books 3.0.2 XSD Schema + Codelists Issue 32.zip". When I run `xjc` on that schema, there is no `ONIXMessageAcknowledgement` class generated.

Can you put together a sample project for me that exposes the problem?

**Comment by stoicflame** [comment] 2016-05-27 19:58
Since a release of 2.4 is imminent and I haven't heard back about this, I'm going to have to move this issue off of the 2.4 release. I'll assign it a new release after I hear more details about how to reproduce the issue.

**Comment by AlexGuion** [comment] 2016-06-03 12:25
Hello,

I check my project and see some issues. So, i will correct it and return to you, as soon as possible.

thanks

**Comment by stoicflame** [comment] 2016-10-28 20:14
No motion on this for weeks. I'll close this until I can get more information to pursue it.

**Closed by stoicflame** 2016-10-28 20:14 UTC
Labels: bug
