### ISSUE TITLE
Data Type empty description

### ISSUE THREAD

**Issue by behzadian** [stoicflame/enunciate#971] opened 2019-07-23 10:29 UTC
I had a class named CreateApplicationDTO as below:
```java
/**
 * Holds information of Application to be create
 */
@Getter
@Setter
//@Builder
public class CreateApplicationDTO extends BaseDto {

    /**
     * Title of Application, mandatory, between 8 and 64 chars
     */
	@NotEmpty
    @Size(min = 8, max = 64)
	public String title;

    /**
     * Description of application, optional, maximum 4000 chars
     */
    @Size(max = 4000)
    private String description;

    /**
     * List of IPs that application and allowed to call B4B methods from
     */
	private List<String> allowedIps = new ArrayList<>();

    /**
     * Indicates app must be enabled after create or disabled
     */
	private boolean enabled = false;

    /**
     * App's password, mandatory, between 8 and 30 chars, must be unique
     */
	@NotEmpty
	@Size(min = 8, max = 30)
	private String secret;

    /**
     * Information about owner user
     */
	@NotNull(message = "error.application.owner-cannot-be-nothing")
	private UserSecurityInformation owner;

    /**
     * List of permissions of app?
     */
	private List<Permission> permissions = new ArrayList<>();

}`

This class is used as parameter type for one RESTApi:

`    /**
     * Creates an application with provided information
     * @param body information of application to be created
     * @return an instance of {@link ApplicationResultDTO} filled with created application information
     */
    @PostMapping
    public ApplicationResultDTO createApplication(
        @ApiParam @Valid @RequestBody CreateApplicationDTO body
    ) {
        final ApplicationResultDTO application = applicationService.createApplication(body);
        return application;
    }
```

but in generated document, description of CreateApplicationDTO is empty:
![FireShot Capture 018 - gateway-service_ CreateApplicationDTO - localhost](https://user-images.githubusercontent.com/6245340/61705109-6e422000-ad5a-11e9-8400-31e2964175cc.png)

What is wrong?

**Comment by panchenko** [comment] 2019-07-23 13:26
The descriptions are available only from sources, so I guess enunciate was not able to find those.

**Comment by panchenko** [comment] 2019-07-23 13:27
The first item in FAQ - https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files

**Comment by behzadian** [comment] 2019-07-24 05:29
I read document, altough `CreateApplicationDTO` is in different module but has same artifact. accroding to documents:

> Maven users will find that the source files of artifacts that have the same groupId as the project were Enunciate is invoked will be included by default

enunciate has access to the src not only bytecode.

plus I added configuration to include sources of module containing class `CreateApplicationDTO` but nothing changed

**Comment by panchenko** [comment] 2019-07-24 14:13
I would suggest running build via `mvn -X` and checking the log. I guess, a possible reasons could be
* a typo somewhere
* some maven plugin is executed too late

**Comment by stoicflame** [comment] 2019-08-06 21:39
I'm just not able to reproduce the problem. Please ensure:

1. The `sources` jar of the module containing `CreateApplicationDTO` is getting built, installed, and deployed.
2. The `groupId` of the module containing `CreateApplicationDTO` is the same as the module generating the Enunciate docs. If not, the module needs to be included using `sourcepath-includes` Maven config.
3. The class is getting covered by the `api-classes` Enunciate configuration.

All three conditions must be met in order for the docs to correctly show up.

If you've confirmed that all three conditions are being met, there's a bug and I need some way to reproduce the issue. Preferably, you could send a patch to [enunciate-sample](https://github.com/stoicflame/enunciate-sample) that would expose the issue.

**Comment by stoicflame** [comment] 2019-08-10 21:40
Since I can't reproduce the problem, I'm closing the issue for now. I'll re-open as needed.

**Closed by stoicflame** 2019-08-10 21:40 UTC
Labels: support
