### ISSUE TITLE
Enunciate.xml config file not having any effect

### ISSUE THREAD

**Issue by bogdanzurac** [stoicflame/enunciate#245] opened 2016-01-08 14:05 UTC
The `enunciate.xml` file appears to be picked up by the gradle plugin, but it has no effect whatsoever on the actual resulting documentation. Now, I don't know if I should've posted this inside the gradle plugin project, as it may be a general issue instead of a plugin based one.

Below is the **enunciate.xml** file inside the root of the project.

```
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.0.0.xsd">

    <title>REST API</title>
    <description>Description here</description>
    <contact>Contact email</contact>
    <copyright>Copyright notice</copyright>

    <modules>
        <enunciate slug="Web App API"
                   version="v1.0"/>

        <jaxrs groupBy="path">
            <application path="/api"/>
        </jaxrs>

        <jackson1 disabled="true"/>
    </modules>

</enunciate>
```

**build.gradle:**

```
tasks.enunciate {
    configFileName = "enunciate.xml"
    File enunciateDistDir = file("src/main/webapp/docs")
    include("**/*.java")
    doFirst {
        enunciateDistDir.deleteDir()
        enunciateDistDir.mkdirs()
    }
    export("docs", enunciateDistDir)
}
```

**Comment by stoicflame** [comment] 2016-01-08 21:13
I'm not a gradle developer, but I can tell you the configuration is applied using Maven and Ant.

What makes you think the file is "picked up" by the gradle plugin if there's no effect?

**Comment by bogdanzurac** [comment] 2016-01-08 21:39
I believe it is being picked up because if I remove the configFileName property and leave the default one of **/src/main/enunciate/enunciate.xml**, but without having the actual file on the path, it complains it doesn't exist, like it should. As soon as I move it inside the folder, the warning disappears. The config still doesn't work, even while using this default file location. Any ideas what could be wrong?

**Comment by stoicflame** [comment] 2016-01-09 00:14
So the file is being _read_ but not applied.

I suspect this is still a bug in the gradle plugin. @jskovjyskebankdk, do you concur?

**Comment by jskovjyskebankdk** [comment] 2016-01-11 06:36
Possibly. But unlikely. I mean, it works for me :)

@bogdanzurac run gradle with -d option. That will show you Enunciate log output.
It'll probably tell us more.

**Comment by bogdanzurac** [comment] 2016-01-12 10:27
The only line that is about the config file from the gradle output is:

```12:19:40.302 [INFO] [org.gradle.api.Task] Using config /home/user/workspace/project/enunciate.xml```

Which is indeed the location of the config file. Is there anything else in particular that I should be looking for? I still believe this isn't caused by the gradle plugin, but rather by a config issue or whatnot. Can you confirm the above config file doesn't have any issues?

**Comment by stoicflame** [comment] 2016-01-12 17:40
The only thing invalid in that config file is this line:

```xml
<enunciate slug="Web App API" version="v1.0"/>
```

The `slug` and `version` attributes should go on the root `enunciate` element. And you'll probably want the slug to not have spaces. Everything else looks good.

What particular configuration elements are you expecting to see but aren't showing up?

**Comment by bogdanzurac** [comment] 2016-01-12 17:52
Removed it, still nothing. I've even left the below version, still doesn't work.

```
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.0.0.xsd">

    <modules>
        <jaxrs groupBy="path">
            <application path="/api"/>
        </jaxrs>

        <jackson1 disabled="true"/>
    </modules>

</enunciate>
```

Even for the above smaller version, I expect the jackson1 module to be disabled, thus the JSON data type to not appear twice on the homepage. And every API path to begin with /api instead of /docs.

For the extended version in the first post, I expect the copyright notice to appear in the footer and the title to be visible up front somewhere. Neither are visible though. So something is definitely wrong.

**Comment by jskovjyskebankdk** [comment] 2016-01-13 07:49
For what it is worth, one of our files looks like the below.
The content is definitely taken into account when generating docs.

'docs' and 'swagger' are the only things we ever generate.

I'm a bit hung up today and tomorrow, so won't have time to look further into it now.

````
<?xml version="1.0" encoding="UTF-8"?>
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.1.0.xsd">
	<title>BuildServer</title>

	<modules>
		<swagger disabled="true" />
		<docs  
			title="" 
			copyright="www.jyskebank.dk" 
			includeDefaultDownloads="false" 
 			applyWsdlFilter="false"
			includeExampleJson="true"/>
			
		<c-xml-client disabled="true" /> 	
		<csharp-xml-client disabled="true" /> 	
		<java-xml-client disabled="true"/>
		<gwt-json-overlay disabled="true" /> 	
		<obj-c-client disabled="true" />
		<obj-c-xml-client disabled="true" />
		<php-json-client disabled="true" /> 	
		<php-xml-client disabled="true" /> 	
		<java-json-client disabled="true" />
		<ruby-json-client disabled="true" />
	</modules>
</enunciate>
````

**Comment by bogdanzurac** [comment] 2016-01-13 10:01
Yeah, well, I've copy-pasted literally the entire code from above and it still doesn't change anything. For example, the Ruby JSON Client (that is the last one being disabled) is still present under the Files and Libraries category as 

```
Ruby JSON Client Library
Created January 8, 2016
```

However, as you can see, the created date is not up to date. Any idea what could be causing that? The title and copyright are still nowhere to be found.

**Comment by jskovjyskebankdk** [comment] 2016-01-13 10:47
I just remembered one thing; there is a dependency problem in the build chain somewhere.

So if you change the build file or enunciate.xml, running the enunciate task may not actually regenerate output.

Try deleting build/enunciate before you run the enunciate task.

**Comment by jskovjyskebankdk** [comment] 2016-01-13 11:02
Ah, I was thinking of #168 which should be fixed.

I still see a dependency problem. I'll have a look at the Gradle task code as it might be caused by something else.

You should still try deleting build/enunciate to see if it makes a difference.

**Comment by bogdanzurac** [comment] 2016-01-13 11:09
Indeed, deleting the /build/enunciate folder in order for it to be regenerated does the trick. Isn't the issue part of the gradle plugin as such?

A few follow-up questions though. Title, description and copyright are visible, but the contact tag info doesn't show up anywhere. Also, the slug tag doesn't have any effect and the version is visible only inside the swagger UI, if I'm not mistaken. Last thing, which is probably the most important one, I'd want to set the full API application path as www.example.com/api, while having the docs path as www.example.com/docs. However, while setting the path as "/api", this results in the actual full path being www.example.com/docs/api. I remember that this used to work without any issues back with Enunciate v1.x, that's why I was confused when I saw the new path with v2.x.

**Comment by jskovjyskebankdk** [comment] 2016-01-13 11:19
I have created stoicflame/enunciate-gradle#5 to track it for the gradle plugin.

**Comment by stoicflame** [comment] 2016-01-13 17:05
> the contact tag info doesn't show up anywhere

It's only applicable to the generated swagger.json file. I'm not sure where it shows up in the Swagger documentation.

> the slug tag doesn't have any effect

It's used to generate the names of some of the html files and generated source code files. It doesn't show up in the documentation.

> version is visible only inside the swagger UI

Correct.

>  I'd want to set the full API application path as www.example.com/api, while having the docs path as www.example.com/docs. However, while setting the path as "/api", this results in the actual full path being www.example.com/docs/api

Try:

```xml
<enunciate>
  <modules>
    <docs docsSubdir="docs"/>
```

Closing this issue; tracking at stoicflame/enunciate-gradle#5.

**Closed by stoicflame** 2016-01-13 17:05 UTC
Labels: bug, support

**Comment by bogdanzurac** [comment] 2016-01-13 17:41
Can confirm the docsSubdir setting works, just as a heads up. Thanks again for everything.
