### ISSUE TITLE
Javadoc from abstract superclasses don't show up in enunciate documentation

### ISSUE THREAD

**Issue by pswvg** [stoicflame/enunciate#223] opened 2015-11-18 10:05 UTC
When generating JAX-RS documentation using 2.1.1, javadoc located at an abstract superclass of a e.g. DTO class don't show up in the documentation.

Either offer an option to ignore the superclasses at all or show them but include the javadoc as well :).

**Comment by stoicflame** [comment] 2015-11-18 18:41
Duplicate of #178.

**Closed by stoicflame** 2015-11-18 18:41 UTC
