### ISSUE TITLE
Spring WEB @ResponseStatus annotation cause Freemarker exception

### ISSUE THREAD

**Issue by charliepjive** [stoicflame/enunciate#327] opened 2016-03-01 10:32 UTC
Hi guys,
I am experiencing a problem with enunciate during my Maven build process.

When a method of a RestController is annotated with @ResponseStatus (Spring web annotation to instruct the controller which HTTP status code to return in case of a successful invocation), the Enunciate Maven plugin fails during Freemarker templates processing.

Here the FTL stacktrace:
[FreeMarkerError.txt](https://github.com/stoicflame/enunciate/files/152548/FreeMarkerError.txt)
Here the Java stacktrace:
[JavaStackTrace.txt](https://github.com/stoicflame/enunciate/files/152550/JavaStackTrace.txt)

Please let me know if I can provide any additional useful info.

Cheers,
Salvatore

**Comment by stoicflame** [comment] 2016-03-01 15:10
Thanks for the report.

**Comment by stoicflame** [comment] 2016-03-11 18:58
Duplicate of #302; fixed at 1fbf68e.

**Closed by stoicflame** 2016-03-11 18:58 UTC
Labels: bug

**Comment by stoicflame** [comment] 2016-03-16 22:30
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
