### ISSUE TITLE
support for grouping rest resources by facet

### ISSUE THREAD

**Issue by theCompanyDream** [stoicflame/enunciate#153] opened 2015-09-22 20:56 UTC
Can Facets only be used to exclude and include generated documentation? I'm trying to give the multiple rest endpoints in our company to be under a different category other than resources. Should i be using facets to do this?
````
@Facet(name = "ContentApi", documentation = "Endpoints dealing with content", value = "ContentApiEndpoints")
package com.babelcentral.bridge.api.content;

import com.webcohesion.enunciate.metadata.Facet;
````

**Comment by stoicflame** [comment] 2015-09-22 22:07
I'm afraid facets can't be used to group resources. Enunciate 1 had some limited capabilities to do this, but that feature never made it into Enunciate 2. The only supported ways to group resources in 2.0 is by resource class or by path.

Shall we consider this issue a feature request to be able to support grouping by facet?

**Comment by theCompanyDream** [comment] 2015-09-23 19:47
Yes that would be pretty awesome. If you don't mind but I would love to ask you a few more questions on your project.

1. Is there a guidelines for contributing to enunciate?
2. Does enunciate possess the ability to see permissions?
3. Why were the files generating the template .fmt instead of .ftl?

**Comment by stoicflame** [comment] 2015-09-23 22:25
> Yes that would be pretty awesome.

Okay. I'm going to rename the issue to better reflect the request.

> Is there a guidelines for contributing to enunciate?

Umm... sure. Policy is "Send me a pull request, we'll hash out any adjustments, and then I'll merge it." :grin:

> Does enunciate possess the ability to see permissions?

You mean things like `@RolesAllowed`, `@DenyAll`, `@PermitAll`, etc.? No. That's being tracked at #62.

> Why were the files generating the template .fmt instead of .ftl?

Because I thought that's how **F**ree**M**arker **T**emplates are named. Is ".ftl" a better convention? Is there somewhere that's stated or implied?

**Comment by theCompanyDream** [comment] 2015-09-24 18:52
>Because I thought that's how FreeMarker Templates are named. Is ".ftl" a better convention? Is there somewhere that's stated or implied? 

I really don't know but I've been using inteillij and it doesn't seem to recognize .fmt as a free marker template I searched all over google to figure out what this was XD.

>Umm... sure. Policy is "Send me a pull request, we'll hash out any adjustments, and then I'll merge it." :grin: 

I laughed at this 

Thank you for the answered questions :)

**Comment by stoicflame** [comment] 2015-09-24 19:18
> inteillij and it doesn't seem to recognize .fmt as a free marker template

Huh. My Intellij does, but that might be because I told it to. I can't remember.

Re-opening since there's still work to do here. (It was probably closed by accident.)

**Comment by theCompanyDream** [comment] 2015-09-25 23:14
OH sorry about that :+1:

**Comment by stoicflame** [comment] 2015-11-02 18:23
Fixed at ca37748d4c9ae6222632d0101fcaaf7a4a637ebc. Use of the `@com.webcohesion.enunciate.metadata.rs.ResourceGroup` annotation is supported for custom resource grouping.

**Closed by stoicflame** 2015-11-02 18:23 UTC
Labels: enhancement

**Comment by stoicflame** [comment] 2015-11-03 21:30
[Enunciate 2.1 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.1.0)

**Comment by jskovjyskebankdk** [comment] 2015-11-04 14:52
Uh, how is this feature supposed to work?

I have a project with several rest resources annotated with @com.webcohesion.enunciate.metadata.rs.ResourceGroup

In enunciate.xml I have:

```
		<docs  
			title="" 
			copyright="www.jyskebank.dk" 
			includeDefaultDownloads="false"
 			applyWsdlFilter="false"
			includeExampleJson="true"/>
			
		<jaxrs groupBy="annotation" />
```

But it does not appear to have an effect on the ordering of services on the index.html page.

Am I misunderstanding the intention of the feature?

**Comment by stoicflame** [comment] 2015-11-04 17:52
Confirmed. The feature was broken. I hate when I'm sloppy like that. [I created a patch release](https://github.com/stoicflame/enunciate/releases/tag/v2.1.1).

**Comment by jskovjyskebankdk** [comment] 2015-11-05 07:42
Fix confirmed. Thanks!

**Comment by nitinsamanta** [comment] 2016-09-26 16:29
Hi..
I am leveraging the ResourceGroup annotation, and custom grouping my REST APIs using groupBy attribute of JAXRS module. One small problem that I am facing is, the APIs which I have not annotated with a custom group are also getting documented in a new category called "Others". Is there any way that i can avoid creation of this group. In short, I dont want those APIs to be documented  which I have not annotated with ResourceGroup. Is there any way I can get this done without using facets for the unwanted  APIs?

**Comment by stoicflame** [comment] 2016-09-26 17:48
> Is there any way I can get this done without using facets for the unwanted APIs?

Well, [you can include/exclude via configuration using classname](https://github.com/stoicflame/enunciate/wiki/Excluding-Including-Classes#configuration), but there's no way to include/exclude based on that annotation. It's easy to add, though. So if you're interested, you're welcome to open up a separate issue to track that request as an enhancement.

But you also don't have to annotate the "unwanted APIs" to exclude them. You could annotate the "wanted" APIs (the ones annotated with `@ResourceGroup`) with an additional `@Facet` annotation and explicitly _include_ that facet via configuration:

```xml
<enunciate ...>
 ...
 <facets>
   <include name="http://mycompany.com/facets#myapi"/>
 </facets>
 ...
</enunciate>
```

**Comment by nitinsamanta** [comment] 2016-09-26 18:01
That helps...thanks :)
