### ISSUE TITLE
Duplicate properties generated with jackson annotation @JsonProperty

### ISSUE THREAD

**Issue by AlbertBui** [stoicflame/enunciate#1043] opened 2020-06-16 01:21 UTC
I wanted to re-raise this issue:
https://github.com/stoicflame/enunciate/issues/909

    @JsonProperty("frontEndProperty")
    private String backendProperty;

Hopefully I can provide more information so this can be successfully replicated. This appears to be happening when using the Jackson annotation `@JsonProperty` and there is a mismatch between the Json value we want on the front end and what we are using on the backend.

    @JsonProperty("backendProperty")
    private String backendProperty;

    @JsonProperty
    private String backendProperty;

If `@JsonProperty` is using the default value or the value set is the same as the property, there is no duplicate entry in the generated swagger.json

**Comment by stoicflame** [comment] 2020-06-16 15:53
Okay, I'll take a look.

As a workaround, consider `delombok`ing (see [plugin usage](http://anthonywhitford.com/lombok.maven/lombok-maven-plugin/usage.html)) have Enunciate run against that, instead of directly against the source code.

**Comment by stoicflame** [comment] 2020-08-27 20:37
I'm really sorry, but I still can't seem to reproduce this. 

Following is a diff I applied to [enunciate-sample](https://github.com/stoicflame/enunciate-sample). Can you tell me how to modify it to expose this problem?

```diff
diff --git a/enunciate-sample-webapp/pom.xml b/enunciate-sample-webapp/pom.xml
index db9e6ab..1251fe7 100644
--- a/enunciate-sample-webapp/pom.xml
+++ b/enunciate-sample-webapp/pom.xml
@@ -32,6 +32,19 @@
         <artifactId>cargo-maven2-plugin</artifactId>
         <version>1.4.14</version>
       </plugin>
+      <plugin>
+        <groupId>org.projectlombok</groupId>
+        <artifactId>lombok-maven-plugin</artifactId>
+        <version>1.18.12.0</version>
+        <executions>
+          <execution>
+            <phase>generate-sources</phase>
+            <goals>
+              <goal>delombok</goal>
+            </goals>
+          </execution>
+        </executions>
+      </plugin>
     </plugins>
   </build>
 
@@ -74,6 +87,12 @@
       <scope>provided</scope>
     </dependency>
 
+    <dependency>
+      <groupId>org.projectlombok</groupId>
+      <artifactId>lombok</artifactId>
+      <version>1.18.12</version>
+      <scope>provided</scope>
+    </dependency>
   </dependencies>
 
 </project>
diff --git a/enunciate-sample-webapp/src/main/java/com/webcohesion/enunciate/sample/rs/PersonsEndpoint.java b/enunciate-sample-webapp/src/main/java/com/webcohesion/enunciate/sample/rs/PersonsEndpoint.java
index 4b5ba9e..ad3aa63 100644
--- a/enunciate-sample-webapp/src/main/java/com/webcohesion/enunciate/sample/rs/PersonsEndpoint.java
+++ b/enunciate-sample-webapp/src/main/java/com/webcohesion/enunciate/sample/rs/PersonsEndpoint.java
@@ -35,8 +35,11 @@ public class PersonsEndpoint {
   }
 
   @POST
-  public void createPerson(Person person) {
+  public void createPerson(MyData person) {
     // ... store the persona in the db...
+    MyData.MyDataBuilder builder = MyData.builder();
+    MyData data = builder.abc("abc").build();
+    //...
   }
 
   @DELETE
diff --git a/enunciate-sample-webapp/src/main/lombok/com/webcohesion/enunciate/sample/rs/MyData.java b/enunciate-sample-webapp/src/main/lombok/com/webcohesion/enunciate/sample/rs/MyData.java
new file mode 100644
index 0000000..cadfe13
--- /dev/null
+++ b/enunciate-sample-webapp/src/main/lombok/com/webcohesion/enunciate/sample/rs/MyData.java
@@ -0,0 +1,22 @@
+/*
+ * © 2020 by Intellectual Reserve, Inc. All rights reserved.
+ */
+package com.webcohesion.enunciate.sample.rs;
+
+import lombok.Builder;
+import lombok.Data;
+import com.fasterxml.jackson.annotation.JsonInclude;
+import com.fasterxml.jackson.annotation.JsonAutoDetect;
+import com.fasterxml.jackson.annotation.JsonProperty;
+
+@Data
+@Builder
+@JsonInclude(JsonInclude.Include.NON_EMPTY)
+@JsonAutoDetect(getterVisibility = JsonAutoDetect.Visibility.PUBLIC_ONLY, setterVisibility = JsonAutoDetect.Visibility.PUBLIC_ONLY)
+public class MyData {
+
+  private String abc;
+  @JsonProperty("frontEndProperty")
+  private String backendProperty;
+
+}
diff --git a/pom.xml b/pom.xml
index 3ac8d52..2837c8d 100644
--- a/pom.xml
+++ b/pom.xml
@@ -12,7 +12,7 @@
 
   <properties>
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
-    <enunciate.version>2.13.0</enunciate.version>
+    <enunciate.version>2.13.1</enunciate.version>
     <jaxws-ri-rt.version>2.2.10</jaxws-ri-rt.version>
     <jackson.version>2.5.3</jackson.version>
     <jaxb.version>2.2.11</jaxb.version>
```

**Comment by sutra** [comment] 2020-12-23 01:27
I have same issue.

**Comment by sutra** [comment] 2020-12-23 16:47
Try  the follow diff, you will get the duplicated `full_name`:

```
diff --git a/enunciate-sample-model/pom.xml b/enunciate-sample-model/pom.xml
index f6489f2..84d9a41 100644
--- a/enunciate-sample-model/pom.xml
+++ b/enunciate-sample-model/pom.xml
@@ -21,6 +21,20 @@
       <groupId>javax.xml.bind</groupId>
       <artifactId>jaxb-api</artifactId>
     </dependency>
+
+    <dependency>
+      <groupId>org.projectlombok</groupId>
+      <artifactId>lombok</artifactId>
+      <scope>provided</scope>
+      <version>1.18.16</version>
+    </dependency>
+
+    <dependency>
+      <groupId>com.fasterxml.jackson.core</groupId>
+      <artifactId>jackson-annotations</artifactId>
+      <version>2.12.0</version>
+    </dependency>
+
   </dependencies>
 
 </project>
diff --git a/enunciate-sample-model/src/main/java/com/webcohesion/enunciate/sample/model/Name.java b/enunciate-sample-model/src/main/java/com/webcohesion/enunciate/sample/model/Name.java
index 186bd44..ec85569 100644
--- a/enunciate-sample-model/src/main/java/com/webcohesion/enunciate/sample/model/Name.java
+++ b/enunciate-sample-model/src/main/java/com/webcohesion/enunciate/sample/model/Name.java
@@ -16,15 +16,22 @@
 
 package com.webcohesion.enunciate.sample.model;
 
+import com.fasterxml.jackson.annotation.JsonProperty;
+
+import lombok.Data;
+
 /**
  * A name of a persona.
  *
  * @author Ryan Heaton
  */
+@Data
 public class Name {
 
   private String givenName;
   private String surname;
+  @JsonProperty("full_name")
+  private String fullName;
 
   /**
    * The given name.
```

**Comment by stoicflame** [comment] 2020-12-28 18:24
@sutra thanks for your help here. I applied your patch, but everything built as expected. Where do I need to look to see the problem?

**Comment by sutra** [comment] 2020-12-29 02:55
> @sutra thanks for your help here. I applied your patch, but everything built as expected. Where do I need to look to see the problem?

Check on my github repository, the [feature/issue-1043](https://github.com/sutra/enunciate-sample/tree/feature/issue-1043) branch.

https://github.com/sutra/enunciate-sample/blob/e382472fbf258da1f3ba7c8e50a5b6fd077ed5f5/enunciate-sample-webapp/target/enunciate-sample-webapp-1.0-SNAPSHOT/json_Name.html#L91

https://github.com/sutra/enunciate-sample/blob/e382472fbf258da1f3ba7c8e50a5b6fd077ed5f5/enunciate-sample-webapp/target/enunciate-sample-webapp-1.0-SNAPSHOT/json_Name.html#L100

**Comment by sutra** [comment] 2020-12-29 08:04
If I add `@JsonAutoDetect(creatorVisibility = Visibility.NONE)` to class Name like below could avoid this duplication:

```
@Data
@JsonAutoDetect(creatorVisibility = Visibility.NONE)
public class Name {
```

**Comment by stoicflame** [comment] 2020-12-29 17:41
I checked out your branch, but I don't know where is the "duplication" that you're talking about. Do I look in the generated documentation for the "Name" data type? Do I look at the client-side code?

**Comment by sutra** [comment] 2020-12-29 17:44
> I checked out your branch, but I don't know where is the "duplication" that you're talking about. Do I look in the generated documentation for the "Name" data type? Do I look at the client-side code?

the `full_name` property.

**Comment by stoicflame** [comment] 2020-12-29 17:51
Where do I look to see the duplication of that `full_name` property? Do I look in the generated documentation for the "Name" data type? Do I look at the client-side code?

**Comment by sutra** [comment] 2020-12-29 17:57
I cannot reproduce it now, but it is duplicated in my another project.

**Comment by sutra** [comment] 2020-12-29 17:57
Like this:
<img width="274" alt="image" src="https://user-images.githubusercontent.com/18538/103303980-618f2480-4a42-11eb-85eb-77add6bf47ac.png">

**Comment by sutra** [comment] 2021-01-13 08:59
Maybe I found the root cause:
``
[ERROR] [ENUNCIATE] 
[ERROR] [ENUNCIATE] Both Jackson 1 and Jackson 2 Enunciate modules are enabled.
[ERROR] [ENUNCIATE] This may cause duplicated and/or inconsistent JSON documentation.
[ERROR] [ENUNCIATE] It is recommended that you disable one of the modules by either
[ERROR] [ENUNCIATE] pruning your classpath of one of the versions of the Jackson
[ERROR] [ENUNCIATE] library, or by explicitly disabling one of the modules in the
[ERROR] [ENUNCIATE] Enunciate configuration file. For more information, see
[ERROR] [ENUNCIATE] https://github.com/stoicflame/enunciate/wiki/Two-JSON-Sections
[ERROR] [ENUNCIATE] 
```

**Comment by stoicflame** [comment] 2021-01-13 15:43
That warning is telling you that Enunciate will be generating two JSON _sections_, but not duplicate properties.

**Comment by stoicflame** [comment] 2021-03-09 21:20
Closing for now until more information can be provided about how to reproduce the problem.

**Closed by stoicflame** 2021-03-09 21:20 UTC
Labels: bug

**Comment by BarysDrahunou** [comment] 2021-07-16 14:07
Have the same problem. In my build.gradle.kts I use plugin `id("com.webcohesion.enunciate") version "2.13.3"` and dependency `classpath("com.webcohesion.enunciate:enunciate-lombok:2.13.3")` 
`enunciate.xml` file looks like:
```
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.13.0.xsd">
                    ...
    <modules disabledByDefault="true">
        <!-- provider modules -->
        <jaxrs disabled="false">
        </jaxrs>
        <jackson disabled="false"/>
        <spring-web disabled="false"/>
        <!-- non provider modules -->
        <docs disabled="false"/>
        <swagger disabled="false" host="localhost:8081">
            <scheme>https</scheme>
        </swagger>
    </modules>
</enunciate>
```
And class looks like 

```
@Data
@Generated
public classClientDetailsDTO {

    @JsonProperty("created_date")
    private Date createdDate;

    @JsonProperty("last_modified_date")
    private Date lastModifiedDate;

    @NotNull
    @JsonProperty("client_id")
    private String clientId;
```
After parsing, part of my `swagger.json` looks like:

 ```
  ...
 "properties": {
		"created_date": {
		  "readOnly": false,
		  "description": "",
		  "type": "integer",
		  "format": "int32"
		},
		"created_date": {
		  "readOnly": false,
		  "description": "",
		  "type": "integer",
		  "format": "int32"
		},
		"last_modified_date": {
		  "readOnly": false,
		  "description": "",
		  "type": "integer",
		  "format": "int32"
		},
		"last_modified_date": {
		  "readOnly": false,
		  "description": "",
		  "type": "integer",
		  "format": "int32"
		},
		"client_id": {
		  "readOnly": false,
		  "description": "",
		  "type": "string"
		},
		"client_id": {
		  "readOnly": false,
		  "description": "",
		  "type": "string"
		},
   ...
```
